### ISSUE TITLE
Some Blocks behave weird

### ISSUE THREAD

**Issue by DasLixou** [Minestom/Minestom#1011]
Some "blocks" like water can be placed normally. but when interacting with like a door or something in the chunk, 

A: The door opens "teleports" a block away and 

B: All Water in the chunk disappears.

But it gets worse: when just putting water at a chunk and then do chunk.getBlock(x, y, z) and there is water, it returns air

**Comment by TheMode** [comment]
What does "putting water means", if you are placing it with a bucket then it is normal. As buckets are not implemented and therefore result in a client-side block only

**Comment by DasLixou** [comment]
:o cause the item isn’t related to the block by default.. ok thanks :D

**Comment by DasLixou** [comment]
Could this be fixed with a BlockPlacementRule?

**Comment by ryleu** [comment]
this should probably be closed and made into a discussion
