### ISSUE TITLE
Inventory Conditions being called for every empty slot when shift clicking an item from player's inventory

### ISSUE THREAD

**Issue by Braayy** [Minestom/Minestom#1012]
I was experimenting with the inventory system and i tried shift clicking an item from my player's inventory into the custom inventory. I've set up the custom inventory to cancel every slot click and to log every condition call just for curiosity and then something strange happened. The inventory condition i'd set up was called for every empty slot of the custom inventory.
When the condition does not cancel the click, it behaves as expected, being called only once for the first empty slot of the custom inventory.

![](https://i.imgur.com/mEAI3hy.png)

**Comment by KrystilizeNevaDies** [comment]
This is expected behaviour, when you shift click, it tries to find any usable slot to put the item in.
