### ISSUE TITLE
Pressing F on item in inventory has weird behaviour

### ISSUE THREAD

**Issue by kiip1** [Minestom/Minestom#1038]
1. Press F on the circled item
![image](https://user-images.githubusercontent.com/25848425/167266138-7027e7eb-a09a-4f42-85c2-32fab4a3bd16.png)
2. Item gets moved to offhand (ghost item) and put in crafting menu (real item)
![image](https://user-images.githubusercontent.com/25848425/167266143-766161b5-2f7b-42e6-8552-8cda67aa4aae.png)

**Comment by Marlonzockt** [comment]
Same as #585
