### ISSUE TITLE
Resource management

### ISSUE THREAD

**Issue by Protonull** [Minestom/Minestom#106]
### What would you like added/changed?
It would be great if extensions had access to an established resource management API. What do I mean by that? Take Bukkit/Spigot/Paper for example and how it handles plugin configs, where config files are stored within the plugin jar and can be saved into the plugin's data folder, and when loading the config, the plugin prefers the data file rather than the internal resource. Though if added, it would be great if this were expanded to any arbitrary file rather than just a specific config file.

### Why do you think this is a good addition/alteration?
It would establish a standard within extensions (that can be made specifically thread safe if necessary) meaning reduced duplicate code, as well as explicit support for data files, particularly human readable data files.

### Why do you want this to be added?
So I can just save / load config files and other such things and get on with making my extension.

**Comment by KrystilizeNevaDies** [comment]
Currently working on an api using MAML, a new file format similar to ini and json, for this.

Although using arbitrary files is simple enough to do without an api, is it not?
