### ISSUE TITLE
Feature: Add kotlinx.coroutines

### ISSUE THREAD

**Issue by nothendev** [Minestom/Minestom#1137]
I am, as a Kotlin programmer, very addicted to using kotlinx.coroutines (even in Minecraft plugins). This is what I mean by adding support for kotlinx coroutines:
- A CoroutineScope property so developers can launch/async from it;
- Suspend listeners (listeners that accept suspend lambdas)
- A suspend function that allows to get T from Acquirable (from suspend context)

**Comment by TheMode** [comment]
I am not really familiar with coroutines, but I'd rather wait for loom's virtual thread

**Comment by MrGazdag** [comment]
i would be against kotlin in the main repo

**Comment by Articdive** [comment]
We already include the kotlin standard library in Minestom, with the hopeful arrival of Loom threads in September however I do believe that this is not necessary.
