### ISSUE TITLE
Instance not loading if different dimension type

### ISSUE THREAD

**Issue by SnowmanFTW** [Minestom/Minestom#1183]
### Discussed in https://github.com/Minestom/Minestom/discussions/1173

<div type='discussions-op-text'>

<sup>Originally posted by **SnowmanFTW** June 19, 2022</sup>
So i have 2 instances like this:
```
        DimensionType dimensionType = DimensionType.builder(NamespaceID.from("minecraft:overworld")).minY(-64).height(400).build();
        MinecraftServer.getDimensionTypeManager().addDimension(dimensionType);
        InstanceContainer spawnContainer = instanceManager.createInstanceContainer(dimensionType);
        spawn = instanceManager.createSharedInstance(spawnContainer);
        spawn.getInstanceContainer().setChunkLoader(new AnvilLoader("spawn"));
        spawn.enableAutoChunkLoad(true);

        InstanceContainer minesContainer = instanceManager.createInstanceContainer();
        mine = instanceManager.createSharedInstance(minesContainer);
        mine.getInstanceContainer().setChunkLoader(new AnvilLoader("mines"));
        mine.enableAutoChunkLoad(true);
```
if i set the spawning instance to spawn, then try to setInstance to mine later, it keeps showing ghost chunks from spawn instance, and keeps saying waiting for chunk in F3 without actually giving me the mine chunks.
but if i set the spawn instance to mine, and try to setInstance to spawn, it works and i can move between them just fine.
anything that i might be doing wrongly? </div>

Okay so after some fiddling with it for a while, i came to the conclusion that with it being like in the discussion, the instance will switch but the chunks will not send, but if the dimension type is the same it will work.

**Comment by Kebab11noel** [comment]
The default dimension type has the same namespace id as you are using (minecraft:overworld) and the client considers it the same therefore it won't trigger the right code paths, so to solve the issue you have to use a different namespace id.
