### ISSUE TITLE
DeclareCommandsPacket crashes client

### ISSUE THREAD

**Issue by RinesThaix** [Minestom/Minestom#1204]
That packet is being sent right at player login to indicate commands available on the server.
#1199 broke something within that packet. I could not simplify my production environment to some test case, but the client crashes with the following (all my commands and their arguments have latin names):
```
<log4j:Event logger="fw" timestamp="1656800593329" level="ERROR" thread="Netty Client IO #8">
    <log4j:Message><![CDATA[Could not deserialize stringcleartargetminecraft:entitytarget]]></log4j:Message>
  </log4j:Event>
XML_ERROR_PARSING_CDATA
```

**Comment by Kebab11noel** [comment]
Fixed by 10a2967
