### ISSUE TITLE
Weird Packet Id ?

### ISSUE THREAD

**Issue by HSGamer** [Minestom/Minestom#1206]
Log & Exception: https://pastes.dev/fJOlZgPfJP

My network is a BungeeCord network.
Sometimes when I join my server implementation of Minestom ([FlexEGames](https://github.com/HSGamer/FlexEGames)), I get these weird packet error and then it kicks me out.
It happens randomly so I don't know why. I tried it locally but couldn't reproduce the exception.

Possible reasons I could think of:
- Somewhere in my implementation was wrong.
- A plugin in my BungeeCord proxy intercepted the connection (Tab plugins?).
- An unknown issue that is not on my side.

**Comment by iam4722202468** [comment]
Closing since this is old. If it can be reproduced on a new version please open a new issue.
