### ISSUE TITLE
Client doesn't receive ArgumentWord restrictions

### ISSUE THREAD

**Issue by TogAr2** [Minestom/Minestom#1217]
Currently, when you use an ArgumentWord with restrictions, the restrictions are not correctly sent to the client.

Steps to reproduce:
- Run the Minestom demo from net.minestom.demo.Main
- Try to use the command /health
- The suggestions 'set' and 'add' should pop up, but they don't

**Comment by TheMode** [comment]
Fixed by 366f08f7f930514aadae0c1a92a78322f7f01530
