### ISSUE TITLE
Falling out of world throws NullPointerException

### ISSUE THREAD

**Issue by deeprobin** [Minestom/Minestom#125]
### What is the current behavior?
Falling out of world in Creative Mode throws many NullPointerExceptions. After some time, you'll get a timeout.

### What is the expected behavior?
Nothing (to implement by user) / or die?
But no NPE log spam

### What steps will reproduce the problem?

Implement event handler like me to your server
```kotlin
val globalEventHandler = MinecraftServer.getGlobalEventHandler()
globalEventHandler.addEventCallback(
    PlayerLoginEvent::class.java
) { event: PlayerLoginEvent ->
    event.setSpawningInstance(instanceContainer)
    event.acquirablePlayer.acquire { player ->
        player.respawnPoint = Position(0.0, 42.0, 0.0)
        player.getAttribute(Attributes.MAX_HEALTH).baseValue = 2F // I don't think this line is the cause, but for completeness I took the code from my example
        player.gameMode = GameMode.CREATIVE
        player.isFlying = true
    }
}
```

### What operating system and java version is being used?
| description           | value                                           |
|-------------------|-----------------------------------|
| operation system | Debian GNU/Linux 9.13 (stretch)  |
| jvm                      | OpenJDK 15.0.1                           |

### If there is an exception, use pastebin/hastebin (NB: no expiry date!) to send the stacktrace
https://ghostbin.co/paste/3ayqe

### Additional information / Possible thoughts on why this bug is happening
NullPointerException / A null check would be helpful

**Comment by TheMode** [comment]
Hmm I am unable to reproduce using https://github.com/Minestom/Minestom/blob/master/src/test/java/demo/MainDemo.java

**Comment by deeprobin** [comment]
Is unfortunately a private project that depends on private Maven repositories. I have nevertheless zipped the Minestom project (I don't have time to create a temporary repository right now). Maybe you can do something with it. [Download of mychunk-server.zip](https://files.deeprobin.de/mychunk-server.zip)
