### ISSUE TITLE
Sidebar doesn't work

### ISSUE THREAD

**Issue by MoritzLeubner** [Minestom/Minestom#1251]
I use this code in my registered loginListener to create a sidebar:
`Sidebar sidebar = new Sidebar(Component.text("aaa"));`
`sidebar.createLine(new Sidebar.ScoreboardLine("some_line_0", Component.text("test"), 0));`
`sidebar.updateLineScore("some_line_0", 1);`
`sidebar.addViewer(player);`
But it doesnt show up to player. (Yes the player object is valid)

**Comment by CryptForge** [comment]
If you set the sidebar before `Player#isActive()` returns true it won't work.
Not sure if this is intended/unavoidable or if it's a bug.

**Comment by Steanky** [comment]
The player is not yet in the world when PlayerLoginEvent is fired, so the required scoreboard packets are not going to be received. Try using PlayerSpawnEvent instead, that should work.

**Comment by MoritzLeubner** [comment]
Thanks both methods work thanks :)
