### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by jglrxavpok** [Minestom/Minestom#128]
### What would you like added/changed?
Minestom lacks tests to ensure its feature work properly.

### Why do you think this is a good addition/alteration?
Having a testing framework for Minestom could allow to avoid regression bugs, make sure features are implemented correctly, and finally, can help Minestom developers (extensions, libraries or server implementations) to test their own code easily.

### Why do you want this to be added?
Testing features inside Minestom can quickly become overwhelming: setting up the server, registering instances, setting up the test and finally writing the test code can take a long time to get right, and needs to be repeated for each test.

### Additional Information
While it is possible to greatly reduce the length of code required via JUnit's `@Before` annotation, using a Minestom-specific framework could go a long way to improve the user experience.

This is heavily inspired by Mojang's own testing framework: https://www.youtube.com/watch?v=vXaWOJTCYNg

**Comment by jglrxavpok** [comment]
Necessary features:
- Independent tests (different classloaders all together?)
- Ability to start a Minestom server very easily just for a test (no manual chunk generation setup to do for instance)
- Assertions
- Test results shown at end of pass (eg 14/42 tests passed)
- Silent when a test passes
- Verbose when a test fails
- Ease of use: no friction, no heavy setup (maybe a custom Gradle if necessary)

Interesting features to have:
- Annotation based (like JUnit)
- Convenience methods to check server state (is my entity at the correct location? Is the chunk loaded?)
- Mini-Pseudo-client to ensure packets are sent correctly

**Comment by redstonedesigner** [comment]
Has there been any update on this recently?  I'm looking to deploy Minestom in a project and the implementation of a testing framework would be ideal to ensure that the code I am asked to deploy is functioning as expected.

**Comment by mworzala** [comment]
> Has there been any update on this recently? I'm looking to deploy Minestom in a project and the implementation of a testing framework would be ideal to ensure that the code I am asked to deploy is functioning as expected.

This has been sort of put on hold. I am currently working on [a more user focused end-to-end framework](https://github.com/mworzala/canary), but its not complete. The goal is to eventually merge these ideas into there.

**Comment by TheMode** [comment]
A testing framework using JUnit has been merged since, still internal for now but enough to close the issue.

We will in the future expand it for third party extensions, and the ability to see all tests running on a single connectable server.
