### ISSUE TITLE
doc(wiki): Scheduler page not up to date

### ISSUE THREAD

**Issue by Distractic** [Minestom/Minestom#1283]
In the wiki, the page about [schedulers](https://wiki.minestom.net/feature/schedulers) has an example code that doesn't work today

```java
Scheduler scheduler = MinecraftServer.getSchedulerManager();
scheduler.scheduleNextTick(() -> System.out.println("Hey!"));
scheduler.submitTask(() -> {
    System.out.println("Running directly and then every second!");
    return TaskSchedule.seconds(1);
});
```

The function `submitTask` cannot receive only one argument
Same for the next code.

```java
Scheduler scheduler = player.scheduler();
Task task = scheduler.scheduleNextTick(() -> System.out.println("Hey!"));
task.cancel();
```

**Comment by TheMode** [comment]
https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/timer/Scheduler.java#L4
https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/timer/Scheduler.java#L67
?

**Comment by Distractic** [comment]
Well, thanks
I will investigate why my IDE didn't find the functions
