### ISSUE TITLE
feat(thread): Current context is Sync or Async

### ISSUE THREAD

**Issue by Distractic** [Minestom/Minestom#1284]
I work on a system who needs to know if in a function (event, command etc..), we're in a SYNC [(ExecutionType.SYNC](https://github.com/Minestom/Minestom/blob/3afc644c5bf92e15b5744593eef592cc30281300/src/main/java/net/minestom/server/timer/ExecutionType.java#L4)) or in ASYNC ([ExecutionType.ASYNC](https://github.com/Minestom/Minestom/blob/3afc644c5bf92e15b5744593eef592cc30281300/src/main/java/net/minestom/server/timer/ExecutionType.java#L5)) context.

Do you think it's possible to add this functionality through the [SchedulerManager ](https://github.com/Minestom/Minestom/blob/3afc644c5bf92e15b5744593eef592cc30281300/src/main/java/net/minestom/server/timer/SchedulerManager.java) ?

**Comment by TheMode** [comment]
async scheduling is no longer available
