### ISSUE TITLE
[Wiki] Chunk Generator redirect broken

### ISSUE THREAD

**Issue by TomJuri** [Minestom/Minestom#1285]
I was reading [this](https://wiki.minestom.net/world/instances) page of the wiki and at the bottom it talked about chunk generators and linked to [this](https://github.com/Minestom/Minestom/wiki/Chunk-generator) page on the GitHub wiki. But that doesn't exist anymore so Instead I just get redirected to the main GitHub page. I'd love to learn about creating my own Chunk Generator, if this page still exists anywhere, let me know.

**Comment by TheMode** [comment]
The wiki has its own repo: https://github.com/Minestom/wiki and you can also PR changes.
