### ISSUE TITLE
test(module): Create module for minestom test framework

### ISSUE THREAD

**Issue by Distractic** [Minestom/Minestom#1286]
Currently, your [test framework](https://github.com/Minestom/Minestom/tree/master/src/test/java/net/minestom/server/api) is only available in Minestom. However, in our projects, we may need to use it for our tests to interact with some Minestom component.

So, do you think it's possible to create a module or project to publish an artifact of the test framework ?

**Comment by TheMode** [comment]
`testing` module has been created
