### ISSUE TITLE
Extensions repository

### ISSUE THREAD

**Issue by Leonardo-DGS** [Minestom/Minestom#130]
Hello, I'd like to know if there is some place where can be found and shared extensions, like SpigotMC for Spigot plugins.

**Comment by KrystilizeNevaDies** [comment]
LeoDog and I are working on this as we speak. To add an extension to the extensions repository, simply tag it with

minestom-extension

This will let the extension go through our automated system and be added to the website.

At the moment, the website is up at [https://package.krystilize.com/](https://package.krystilize.com/extensions)

**Comment by Leonardo-DGS** [comment]
@KrystilizeNevaDies the extensions will support all Minestom servers? If it is so, you can build a custom server, but you don't have to waste a lot of time reinventing the wheel!

**Comment by jglrxavpok** [comment]
We cannot guarantee 100% compatibility, especially if the extensions start modifying bytecode at runtime, but the idea is that extensions do prevent reinventing the wheel as much as possible.

**Comment by Leonardo-DGS** [comment]
Thank you!
