### ISSUE TITLE
Fluid blocks' level property is inverted

### ISSUE THREAD

**Issue by TogAr2** [Minestom/Minestom#1356]
The property "level" of fluid blocks is sent inverted to the client. This is supposed to be a water stream with level values gradually going down, but instead they are going up on the client (but are correct server side).
The first block is correct, because it is the default water block, which has "level" set to 0 (which on the client on the f3 screen displays as the water not having any properties).

<img width="1512" alt="" src="https://user-images.githubusercontent.com/59421074/185809173-9f9a8bf3-1b2d-4619-ae57-a3e90d4aa332.png">

**Comment by GoldenCookieGIT** [comment]
![image](https://user-images.githubusercontent.com/45347578/185810400-f2ca0b42-1f0d-4ea3-83ce-3cf11bd667a5.png)
![image](https://user-images.githubusercontent.com/45347578/185810428-b28a509c-e8d8-481e-9701-7e2942b4e3d6.png)
(blue is vanilla, pink is minestom)
seems to be the same as vanilla. As for the falling property you need to set the level to be 8+

**Comment by TogAr2** [comment]
Thank you for telling me about the falling property, however the levels are still inverted for me.
`Block.WATER.withProperty("level", "7")` results in water with level 1.

(I am using master)

**Comment by GoldenCookieGIT** [comment]
gradually going down is 0, 7, 6, 5, 4, 3, 2, 1. are you sure youre doing it in that order?
a reproducer would be nice

this is how i generated my water stream so make sure youre just not doing 0, 1, 2, 3, 4, 5, 6, 7
```kotlin
(0..7).forEach {
    player.instance!!.setBlock(
        player.position.add(0.0, 0.0, it.toDouble()),
        Block.WATER
            .withProperty(
                "level",
                it.toString()
            )
    )
}
```

**Comment by TogAr2** [comment]
Correct me if I am wrong, but your water stream seems to be going 0, 1, 2, 3, 4, 5, 6, 7, the further away from the player the higher the number.

Anyways, a simple reproducer would be what I said earlier: `Block.WATER.withProperty("level", "7")` and then checking the client side value by using the f3 menu.

**Comment by GoldenCookieGIT** [comment]
refer to my screenshots, i labeled each water block what level they are

**Comment by GreatWyrm** [comment]
It appears to be a weird property of Minecraft
https://bugs.mojang.com/browse/MC-159468
