### ISSUE TITLE
Possibly simplify initializing block alternatives, which could help with Block States API later on?

### ISSUE THREAD

**Issue by MichaelPriebe** [Minestom/Minestom#136]
Here's an example of code that can generate all the magic ids of block states by only providing the default: https://gist.github.com/MichaelPriebe/c4c9c24e37ef25073f3dbf43946a5cd3

Its output matches all the traditionally hardcoded states: https://github.com/Minestom/Minestom/blob/master/src/autogenerated/java/net/minestom/server/instance/block/states/OakStairs.java

I am not sure how it would be implemented though, but it could lead to a more enjoyable usage of block states, instead of funky "key=value" lists.

**Comment by TheMode** [comment]
One issue with this approach could be memory consumption. It does create a bunch of unnecessary objects
