### ISSUE TITLE
Entity Velocity Packet spam

### ISSUE THREAD

**Issue by Arektor** [Minestom/Minestom#1413]
Any entity affected by gravity will cause all its viewers to receive an entity velocity packet **per tick**, even when perfectly still. An amount of packets that can quickly rise to absurd levels the more entities and players you add.
These packets however seem to be completely unnecessary, and to be safely skippable without any side effect.

Skipping these unnecessary packets can be achieved simply by commenting out line 596 of Entity, in function velocityTick:
`if (!isPlayer) sendPacketToViewers(getVelocityPacket());`
 
  
 
Please note however that my testing so far might not have been as extensive as it could've been, and consists of the following:
- An EntityCreature of type Zombie with NoGravity set to false - gravity seems to still be perceived just fine client-side with the fix, whether it is after knockback or simply falling from spawn or broken block.
- An EntityCreature of type Zombie with NoGravity set to true - the issue doesn't affect NoGravity entities in the first place, and the fix doesn't seem to affect any of the perceived behavior client-side.

**Comment by TheMode** [comment]
I believe that such packets are sent every X ticks in vanilla, do we really want to completely remove it?

By the way you may be interested in our [testing framework](https://github.com/Minestom/Minestom/tree/master/src/test/java/net/minestom/server/entity) (all files ending with `IntegrationTest`)

**Comment by Arektor** [comment]
The idea that it would be vanilla behavior completely skipped over my head, but after a few tests both on a paper and on a vanilla server, it isn't the case.

Paper (1.19.2):
https://user-images.githubusercontent.com/6461173/191709940-c9b81d1e-c3b7-46d8-ab85-bcfd3758c7a3.mp4

Vanilla (1.18.1):
https://user-images.githubusercontent.com/6461173/191710317-804cb1c7-51ac-46b1-91c1-3ce0397e7bc0.mp4
(note for this one, the entity velocity packet seems to be net.minecraft.class_2743, which does not appear on the logs because the entity does not move. There's also a slight but unlikely possibility for it to be net.minecraft.class_2684$class_2685, which appears about 2-3 times.)

 

I also tested how often the velocity packet would be sent when the entity is falling from gravity. On both paper and vanilla server, it would be sent every 150ms - so, every 3 ticks.

Regarding the testing framework... I actually have no idea how to use one😅Will try to look into it though

**Comment by TheMode** [comment]
> Regarding the testing framework... I actually have no idea how to use one😅Will try to look into it though

The testing API is currently internal, so you would have to fork the repo. Otherwise it is pretty straightforward, feel free to ask anything on discord.
