### ISSUE TITLE
Player's disappear in certain areas randomly

### ISSUE THREAD

**Issue by Tofaa2** [Minestom/Minestom#1415]
I have all 3 via's for comparibility and whenever i load my chunks then the map and teleport players the players become invisible. I decided to try updating a player's viewable players and add there and remove and readd but still in certain chunks the client just has entities that disappear. Not sure if it's a bug on my end or viaversions but I'm guessing it's the second one since the features work on their own

**Comment by mudkipdev** [comment]
Did you solve the issue? You should leave your solution here for other people that may be having the same problem in the future.

**Comment by Tofaa2** [comment]
> Did you solve the issue? You should leave your solution here for other people that may be having the same problem in the future.

No i have not, I forgot i accidentally made this in the issues area therefore i closed it and reoppened in discussions.
