### ISSUE TITLE
Shutdown in pterodactyl 

### ISSUE THREAD

**Issue by DevBlokJochem** [Minestom/Minestom#1420]
When I press on "shutdown", the server doesnt stop. This is annoying, because my database is crashing if the server got killed.

**Comment by ZakShearman** [comment]
Have you set up a shutdown command on your server? The shutdown on pterodactyl for Paper just runs `stop`(see https://github.com/parkervcp/eggs/blob/master/stock_eggs/minecraft/egg-paper.json#L22)

**Comment by DevBlokJochem** [comment]
> Have you set up a shutdown command on your server? The shutdown on pterodactyl for Paper just runs `stop` (see https://github.com/parkervcp/eggs/blob/master/stock_eggs/minecraft/egg-paper.json#L22)

Oke, are there other commands pterodactyl can run?

**Comment by dev-hydrogen** [comment]
> Have you set up a shutdown command on your server? The shutdown on pterodactyl for Paper just runs `stop` (see https://github.com/parkervcp/eggs/blob/master/stock_eggs/minecraft/egg-paper.json#L22)

wouldnt this require a stop command being implemented on the server?

**Comment by KrystilizeNevaDies** [comment]
> > Have you set up a shutdown command on your server? The shutdown on pterodactyl for Paper just runs `stop` (see https://github.com/parkervcp/eggs/blob/master/stock_eggs/minecraft/egg-paper.json#L22)
> 
> Oke, are there other commands pterodactyl can run? (I think not)
> 

Yes you can create a custom egg that stops the server using whatever commands you want.

**Comment by doomslayer6000** [comment]
I think you can just create stop command at make it stop server like this?
https://github.com/off-by-0point5/minestom-lobby/blob/master/src/main/java/com/github/offby0point5/minestom/command/StopCommand.java
