### ISSUE TITLE
Player is invisible after Respawn

### ISSUE THREAD

**Issue by FlxwDNS** [Minestom/Minestom#1480]
Hello, if a player respawn, the play cant see the other players!

**Comment by GreatWyrm** [comment]
Can you clarify a bit futher?

The title implies other players cannot see the respawned player, but your description states that the respawned player does not see other players.

**Comment by FlxwDNS** [comment]
So when a player respawns he just can't see the other players.

**Comment by FlxwDNS** [comment]
https://youtu.be/svnksBSYXzY
