### ISSUE TITLE
Velocity Y is always negative 

### ISSUE THREAD

**Issue by MrBretze** [Minestom/Minestom#1486]
Hello, i have made a custom Jump event for my server but i can detect that in this last version because the player.getVelocity().y() is always negative...

My code is here: 
```java
        EVENT_HANDLER.addListener(PlayerMoveEvent.class, event -> {
            var player = event.getPlayer();
            var velocity = player.getVelocity();
            SpaceDumpServer.broadcastMessage("Velocity Y = " + velocity.y());
            if (velocity.y() > 0) {

                // Default jump velocity
                float jumpVelocity = 8.3999997F; // Default jump velocity

                if (PotionUtils.hasPotionEffect(PotionEffect.JUMP_BOOST, player)) {
                    // If player has jump potion add it to jump velocity
                    jumpVelocity += (PotionUtils.getPotionEffectLevel(PotionEffect.JUMP_BOOST, player) + 1F) * 2F;
                }

                // Check if player is not on ladder and if jump velocity calculated is equals to player Y velocity
                if (Float.compare((float) velocity.y(), jumpVelocity) == 0) {
                    MinecraftServer.getGlobalEventHandler().call(new PlayerJumpEvent(player));
                }
            }

        });
```

**Comment by TheMode** [comment]
The behavior of entity/player velocity have been made the same to avoid unnecessary confusion. The negative value you are noticing correspond to gravity. `setVelocity` also affect it.

In this case I assume that you are more interested in movement delta.

**Comment by MrBretze** [comment]
But so who I can detect now only the jump (when I press the jump key) ??
I understand what do you say, but in this case, is not the gravity or the player need two integration of that, one named "velocity" and one "gravityVelocity" my sample code is totally work on 1.18.2

**Comment by TheMode** [comment]
I assume with the position delta. The client doesn't explicitly signal jumps.
