### ISSUE TITLE
There is a bug in PlayerUseItemEvent 

### ISSUE THREAD

**Issue by CharkTekk** [Minestom/Minestom#1503]
Hallo :)
There is a bug in PlayerUseItemEvent the problem is if you look at the ground and don't have an item in your hand it won't be triggered as well as in PlayerUseItemOnBlockEvent it won't be triggered please fix it

**Comment by Obyvante** [comment]
I couldn't understand your issue. Use "Item" event requires the player to use an item. Obviously, it won't work if you are not holding any item.

Could you describe your problem if what I say doesn't make sense?

**Comment by iam4722202468** [comment]
Closed, works as intended
