### ISSUE TITLE
Game data

### ISSUE THREAD

**Issue by TheMode** [Minestom/Minestom#153]
The goal is to remove our dependency on prismarine minecraft-data and Mojang data generators.

It might also allow us to become registry-based instead of generating enums. Allowing users to create their own blocks, entities, etc... with a modded client.

Here is our wish list of fields to retrieve from the vanilla client.

## Blocks
- id
- display name
- hardness
- bounding box information (even for complex shapes such as stairs)
- id for every state
- Block Entity namespace id
- luminance (emitted light)
- opacity (consumed light)

## Entity types
- id
- display name
- bounding box

## Items
- id
- Max default stack size
- Corresponding block

## Map Colors
- name
- id
- colorValue

**Comment by jglrxavpok** [comment]
# Additional info
## Blocks
* BlockEntity namespace id

## Items
* id
* Max default stack size
* Corresponding block

**Comment by Articdive** [comment]
Now closed by #309
