### ISSUE TITLE
Potion effects on entities are not visible to the client

### ISSUE THREAD

**Issue by Steanky** [Minestom/Minestom#1546]
Tested on e5d0a43.

Code used to spawn the entity is below:

```java
Entity entity = new Entity(EntityType.ZOMBIE);
entity.setInstance(player.getInstance(), player.getPosition()).join();
entity.addEffect(new Potion(PotionEffect.GLOWING, (byte)0, 10000, Potion.PARTICLES_FLAG));
```

The glowing effect does not appear on the client and no particles are visible. 

This issue seems to apply to all effect types, not just `GLOWING` (I specifically tested `INVISIBILITY` too), and appears to happen with many different values chosen for the amplifier, duration, and various flags besides the ones shown.

General info:
1) I'm testing on a fork, but it doesn't modify anything related to entity effect packets.
2) I have tested both connecting through Velocity and directly to the server, with identical results.
3) Effects work when given to players.

**Comment by mworzala** [comment]
Effects on players are handled by the client, effects on entities are handled by the server. Minestom does not do this. For example, glowing and invisibility are both entity metadata flags which need to be set (`Entity#setGlowing` and `Entity#setInvisible` respectively)
