### ISSUE TITLE
Implement the Adventure API

### ISSUE THREAD

**Issue by kezz** [Minestom/Minestom#156]
Adventure is a server-side user interface library for Minecraft which is fast becoming the standard user interface system for many Minecraft related projects. It is currently implemented in [Velocity](https://velocitypowered.com/), [Sponge 8](https://www.spongepowered.org/) and [Paper](https://papermc.io/).

Moving to use Adventure has the following benefits:
- Brings Minestom into step with other server implementations.
- Allows developers to move projects to Minestom more easily.
- Reduces all user interface maintenance in Minestom.
- Future-proofs Minestom developers against upcoming changes (for example, the upcoming Title changes).
- Allows developers to use the advanced API that Adventure provides.

**Comment by mworzala** [comment]
This has been discussed in Discord many times, and as far as I am aware there has been no change in stance on the subject.

I think it's likely that this is a waste of time at the moment. That being said, [this](https://github.com/mworzala/adventure-platform-minestom) may be a helpful reference.

**Comment by TheMode** [comment]
I personally still do not get the advantage over a wrapper as the one @mworzala did.
But well I get the concern and the fact that it will help to reduce maintenance

**Comment by kezz** [comment]
Closed with #157
