### ISSUE TITLE
Get all registered listeners

### ISSUE THREAD

**Issue by Distractic** [Minestom/Minestom#1592]
# Context

In my project, I need to retrieve all registered listeners from GlobalEventHandler.
We can add or remove but it's not possible to get the listeners.

Is it possible to implement this function ?

**Comment by mworzala** [comment]
What is the use case, this does not seem like a good feature to me.

**Comment by Distractic** [comment]
> What is the use case, this does not seem like a good feature to me.

I need to check if exactly a list of listeners is registered. With the exacte number of listeners, same type etc.

**Comment by mworzala** [comment]
(kind of a necropost, I know)
We generally suggest not adding/removing listeners a lot and instead filtering what you need with an EventFilter on the nodes or listeners.
