### ISSUE TITLE
Anvil loader don't use registred chunk supplier

### ISSUE THREAD

**Issue by masmc05** [Minestom/Minestom#1634]
https://github.com/Minestom/Minestom/blob/91a344aa9239e05becbbedac8675b441c325b6f5/src/main/java/net/minestom/server/instance/AnvilLoader.java#L104

here it creates a dynamic chunk instead of using registred chunk supplier

Could you make it use registred chunk supplier, or allow setting the chunk supplier there

**Comment by iam4722202468** [comment]
This has been fixed
