### ISSUE TITLE
Attacker yaw value can infinitely increase/decrease

### ISSUE THREAD

**Issue by ZakShearman** [Minestom/Minestom#168]
### What is the current behavior?
A player's yaw when you call `player.getPosition().getYaw()` can be under 0 or over 360. You can rotate and it can infinitely increase/decrease based on the direction you rotate in.

I doubt a video is needed but in case: <https://zak.pink/2021/03/Frayed-Arachnid-11486.mp4>

### What is the expected behavior?
The rotation should roll over on itself. E.g -1 -> 359 and 365 -> 5.

### What steps will reproduce the problem?
Rotate a couple times in the same direction and your yaw will either be under 0 or over 360.

### What operating system and java version is being used?
Windows 10, Java 11 Azul

**Comment by TheMode** [comment]
Those are actually the values given by the client.
I do however agree that this is not ideal.

Do you think that the angle should map between 0/360 or -180/180? The only change should be a small conversion here https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/utils/Position.java#L366 (same for pitch)

**Comment by ZakShearman** [comment]
IMO it should be 0/360 but I'd like to see more input to see, especially from people that've practically used yaw before with spigot or whatever.

**Comment by Eoghanmc22** [comment]
I think it would make sense to use the same values as in f3 on the client. Which is 180 - -179. Just make sure there is a utils function to find the true distance between 2 angles.

**Comment by TheMode** [comment]
Fixed by #231
