### ISSUE TITLE
Change ItemStack in PickupItemEvent to ItemEntity

### ISSUE THREAD

**Issue by stefvanschie** [Minestom/Minestom#169]
### What would you like added/changed?
Currently the PickupItemEvent contains information about the ItemStack that is being picked up. This ItemStack is the underlying ItemStack from the ItemEntity that is actually being picked up. My proposed change is to replace this ItemStack with ItemEntity. The exact changes would be: replacing the `ItemStack itemStack` field in the PickupItemEvent to `ItemEntity itemEntity`; replacing  the current constructor's second parameter (`ItemStack itemStack`) to `ItemEntity itemEntity`; and replacing the `ItemStack getItemStack()` method with a `ItemEntity getItemEntity()` method, which returns the `itemEntity` field.

### Why do you think this is a good addition/alteration?
This change should be made to allow users to interact with the item entity being picked up, rather than being restricted to the underlying ItemStack. Users who still wish to interact with the underlying ItemStack can call `ItemEntity#getItemStack()` to retrieve the underlying ItemStack.

### Why do you want this to be added?
In the extension I'm making I want to alter the behaviour in which players pickup item entities. Since this change results in players not picking up items in the traditional way, the PickupItemEvent would be cancelled. However, the ItemEntity they are picking up may in some cases need to be deleted. Since there's currently no way to access the ItemEntity being picked up, I am unable to delete this item.

### Additional Information
I've asked about this in the Discord guild previously, however I think it was forgotten about, hence why I raise this here.

**Comment by TheMode** [comment]
No complaint in my case

**Comment by TheMode** [comment]
Done in d6683932c8345426d2ce85526fcd31a1adbcdd75
