### ISSUE TITLE
ghost players in offline mode

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [Minestom/Minestom#178]
### What is the current behavior?
When a player leaves and joins an offline server quickly, a clone of the player is created

### What is the expected behavior?
That the previous player entity leaves before the next one joins

### What steps will reproduce the problem?
leave and join a server with mojang auth disabled in quick succession

### What operating system and java version is being used?
windows 10 java 11

### Additional information / Possible thoughts on why this bug is happening
Probably due to a netty channel not being terminated correctly

**Comment by Geolykt** [comment]
> leave and join a server with mojang auth enabled in quick succession
I think you mean disabled

**Comment by JRedOW** [comment]
I had this happen to me during testing with a group.  He did not disconnect, rather he joined the world, then was quickly kicked.  He never told me the message, but a version of him floated at the spawn point.  He then rejoined, yet the floating "player" was still there.

**Comment by TheMode** [comment]
Fixed in the current in-progress branch.
