### ISSUE TITLE
Jitter on fast moving snowball

### ISSUE THREAD

**Issue by KianBrose** [Minestom/Minestom#1791]
Issue is exactly as described, can be seen in this video:
https://cdn.discordapp.com/attachments/706186227493109860/1086314556944560220/2023-03-17_16-45-11ee.mp4
https://cdn.discordapp.com/attachments/706186227493109860/1086326348479467620/2023-03-17_17-32-33.mp4

It doesn't move normally and it's not video lag, it's just janky movement

Edit, confirmed it's not a client side issue, the same code on PaperMC produces this:
https://cdn.discordapp.com/attachments/706186227493109860/1086322166267662386/2023-03-17_17-14-49ee.mp4

Update:
At TheMode's suggestion, I tried setting the gravity metadata of the entity instead of using Entity#setNoGravity 
```java
EntityMeta bmetadata = bulletEntity.getEntityMeta();
bmetadata.setHasNoGravity(true);
```
UPDATE: This section is no longer accurate, after further testing it seems that the jitter remains when shooting horizontally
It produces the following
https://cdn.discordapp.com/attachments/706186227493109860/1086328062997712976/2023-03-17_17-39-35.mp4
The left/right jitter is essentially gone, the only remaining issue being that it seems to "suddenly stop" and then teleport forward every now and then as seen here:
https://cdn.discordapp.com/attachments/706186227493109860/1086329530286882927/2023-03-17_17-43-25ee.mp4

New update:
Did more testing with papermc and minestom, confirmed to be a minestom issue as paper does not replicate the jittery behavior:
https://cdn.discordapp.com/attachments/706186227493109860/1086342326743486597/2023-03-17_18-34-16ee.mp4

**Comment by MelonHell** [comment]
Should be fixed 
7cbce377a70ccc2b972391ea7ef566af71b20d3f

**Comment by KianBrose** [comment]
https://github.com/KianBrose/MinestomMcWar/tree/physics-projectile-pre


This custom branch fixes all projectile issues I had with minestom including hitboxes, there was an issue where things were hitting things behind walls if hit from a corner
