### ISSUE TITLE
ProjectileEntity physics broken in several ways

### ISSUE THREAD

**Issue by KianBrose** [Minestom/Minestom#1808]
As seen in these two videos:

https://cdn.discordapp.com/attachments/706186227493109860/1090058047323394088/bug2.mp4
https://cdn.discordapp.com/attachments/706186227493109860/1090751851915387000/2023-03-29_23-18-5ee1.mp4

A ProjectileEntity completely fails to trigger either ProjectileCollideWithEntityEvent or ProjectileCollideWithBlockEvent for unknown reasons.

Possible cause (what I suspect), the onStuck function for ProjectileEntity does not function properly

Full test case server:

**Comment by iam4722202468** [comment]
Use PlayerProjectile
