### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by Addy4ever** [Minestom/Minestom#1869]
Recipes are being sent out incorrectly in recent builds.

Minestom Version used: 954e8b3915 (1.19.3)
Client used: Vanilla 1.19.3

How to reproduce:
- register a recipe

Code used to create the recipe:

```java
ItemStack input = ItemStack.builder(Material.DIAMOND).build();
ItemStack output = ItemStack.builder(Material.DIAMOND_BLOCK).build();
DeclareRecipesPacket.Ingredient ingredient = new DeclareRecipesPacket.Ingredient(List.of(input));

ShapedRecipe shapedRecipe = new ShapedRecipe("minecraft:test", 3, 3, "", List.of(ingredient, ingredient, ingredient, ingredient, ingredient, ingredient, ingredient, ingredient, ingredient), output) {
    @Override
    public boolean shouldShow(@NotNull Player player) {
        return true;
    }
};

MinecraftServer.getRecipeManager().addRecipe(shapedRecipe);
```

![Screenshot 2023-06-04 191902](https://github.com/Minestom/Minestom/assets/74501449/a634e5fc-7c4a-4a16-afbf-c89704ad4d24)

I've noticed that this bug only occures in the recent 1.19.3 builds. The last build that supports 1.19.2 seems to be unaffected.

**Comment by mworzala** [comment]
<img width="858" alt="Screenshot 2024-02-09 at 4 04 29 PM" src="https://github.com/Minestom/Minestom/assets/35708499/9a43b6b4-808e-4510-8532-1b962614c584">

Cannot repro, so I am assuming this is fixed.
