### ISSUE TITLE
Entity head rotation doesn't update on teleport

### ISSUE THREAD

**Issue by ZakShearman** [Minestom/Minestom#1881]
The entity head rotation packet (EntityHeadLookPacket) on teleport is only sent by the setView method. However, this never gets sent because the position has already been updated so it fast exits.

Don't have time to do this right now so if anyone wants to look at it :)

**Comment by TheMeinerLP** [comment]
Have you code to repdroduce it ?

**Comment by GreatWyrm** [comment]
Could you try to reproduce it with the latest commit? It may be fixed now

**Comment by iam4722202468** [comment]
This is fixed
