### ISSUE TITLE
Block commands API & new world format

### ISSUE THREAD

**Issue by TheMode** [Minestom/Minestom#189]
Integrating a list of well-defined block commands (eg fill/schematic/noise) with the following traits:
* Serializable
* Convertable to command syntax
* Usable in code using block command buffers
* Provide notable performance improvement by taking advantage of the predictable expect of those (eg fill a whole section with stone instead of setting each block one by one)

Those commands could also be used to serialize chunks and therefore be part of a new world format

**Comment by AwesomestCode** [comment]
Should this be an official extension or part of the lib itself?

**Comment by TheMode** [comment]
Probably in the main repo in order to get the potential performance improvements, and make it an alternative for current batches

**Comment by mworzala** [comment]
This is unlikely to end up in the main repo, closing for now.
