### ISSUE TITLE
Deploy to a real repository, not to jitpack

### ISSUE THREAD

**Issue by MrIvanPlays** [Minestom/Minestom#1891]
A few times in a row we need to change the Minestom dependency version in Treasury because of jitpack.
Please migrate to a real repository (for example deploying to maven central).

**Comment by MrGazdag** [comment]
This was planned, although they said “only when Minestom reaches a more stable release”, but not much activity is happening anymore on the repo

**Comment by LooFifteen** [comment]
project seems stable to me

**Comment by MasterBroNetwork** [comment]
For those of you who aren't liking Jitpack, If you aren't using extensions or the built-in logger, I recommend using [Minestom-CE](https://github.com/hollow-cube/minestom-ce) for now until activity on Minestom's own repository picks back up.

**Comment by mworzala** [comment]
Minestom CE is merged in #1937
