### ISSUE TITLE
Firing snowballs does not remove items from inventory properly

### ISSUE THREAD

**Issue by Nuckerr** [Minestom/Minestom#1896]
![javaw_CohsyZ8IdC](https://github.com/Minestom/Minestom/assets/62883418/30c8f1c9-e7ed-4d59-a392-f5e5d08dae10)

While developing my spleef game, I discovered this bug:
By default, minestom removes snowballs from your inventory when right click them. However, it seems they are not properly being removed (is my assumption, I'm not familiar with how minestom actually works with items).

If I throw these snowballs, say I had 16, and throw 4, then I end up with 12. Except if I open my inventory, or when you cause the inventory to be updated (I think), all the snowballs just thrown reappear. So you end up with 16 again.

**Comment by mworzala** [comment]
Minestom is not removing the snowballs, it's client prediction. You must implement this.

**Comment by Nuckerr** [comment]
Okay, thanks
