### ISSUE TITLE
Update to 1.19.4 ?

### ISSUE THREAD

**Issue by HolyPacket** [Minestom/Minestom#1914]
Please Update from 1.19.3 to 1.19.4

**Comment by MasterBroNetwork** [comment]
This is less of an issue and more of a request but a valid one at that.
1.19.4 is more complicated than you would think despite it being a minor release unlike 1.20 due to features such as display entities and their unique properties such as interpolation information.

**Comment by mworzala** [comment]
#1937 is now merged, so 1.20.4 is supported.
