### ISSUE TITLE
How to make lightning chunk?

### ISSUE THREAD

**Issue by WilliamPhysics** [Minestom/Minestom#1921]
when I add LightningChunk to the suppiler chunk, the chunk is sent without light first, and then with light, this creates a very heavy load on my network

**Comment by iam4722202468** [comment]
How are you measuring the network load? What packets are being sent, what are the sizes and contents of the packets, how often are they being sent, etc. ? Sending the chunk then lighting should make very little difference, as only lighting data is sent the second time, not the entire chunk. This lighting data is not sent with the initial chunk.
