### ISSUE TITLE
Setting a player skin will reset potion effects

### ISSUE THREAD

**Issue by Traquolix** [Minestom/Minestom#1922]
Hello,
I think I noticed a weird bug.
When we set a player skin / reset the skin, potion effects disappear.

Command used to add potion effect to a player :
```java
private void execute(@NotNull CommandSender commandSender, @NotNull CommandContext commandContext) {
        Player player = (Player) commandSender;

        // Add the night vision effect to the player with infinite duration and no amplifier
        player.addEffect(new Potion(PotionEffect.NIGHT_VISION, (byte) 0, Integer.MAX_VALUE, Potion.ICON_FLAG));

        logger.info("[Player] - " + player.getUsername() + " got night vision forever.");
    }
```
Code to set the player skin :
```java
PlayerSkin playerSkin = PlayerSkin.fromUuid(String.valueOf(player.getUuid()));
        player.setSkin(playerSkin);
```
Code to set the player skin.

**Comment by LooFifteen** [comment]
As seen [here](https://github.com/Minestom/Minestom/blob/c5047b803771686979be96e1cbeecb349a48f014/src/main/java/net/minestom/server/entity/Player.java#L981-L993), when changing the skin, the player is respawned. This will cause the client to believe it is a completely different entity, causing it to lose its potion effects. You'll either need to send the potion effects again after setting the skin or make Minestom restore the player status by default.
