### ISSUE TITLE
CommandParserImpl#collectArguments does not skip subcommand

### ISSUE THREAD

**Issue by UserUNP** [Minestom/Minestom#1927]
https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/command/CommandParserImpl.java#L72

example input: `cmd subcmd arg`  
expected nodeResults: `[subcmdResult, argResult] -> .stream().skip(1) -> [argResult]`  
actual nodeResults: `[cmdResult, subcmdResult, argResult] -> .stream().skip(1) -> [subcmdResult, argResult]`

when i was testing `argResult` was `SyntaxError` and i had a suggestion callback and `subcmdResult` was `Success`

**Comment by spannerdev** [comment]
Was this fixed by #1893 ?

**Comment by UserUNP** [comment]
Yes
