### ISSUE TITLE
Unable to use PlayerSkin#fromUsername

### ISSUE THREAD

**Issue by WixiDev** [Minestom/Minestom#1978]
Sometimes when I join the server, I get [this](https://paste.md-5.net/ikelemebor.sql) stacktrace. this is my code:

```java
val myProfileItem = ItemStack.builder(Material.PLAYER_HEAD)
               .displayName(parseString("<green>My Profile <gray>(Right Click)"))
               .build();

globalEventHandler.addListener(PlayerLoginEvent.class, event -> {
    // ...

    val myProfileWithMeta = myProfileItem.withMeta(PlayerHeadMeta.class, playerHeadMeta -> playerHeadMeta
                   .skullOwner(player.getUuid())
                   .playerSkin(PlayerSkin.fromUsername(player.getUsername()))
    );

    player.getInventory().setItemStack(1, myProfileWithMeta);
});
```

**Comment by WixiDev** [comment]
this issue will be caused if API isn't responsible. It could have a custom exception for it, so nobody gets confused like me.

**Comment by ItsRemix** [comment]
It happens only if you join server too soon after restart

**Comment by WixiDev** [comment]
I used this code somewhere else, and I still get this error.

**Comment by GreatWyrm** [comment]
I would highly recommend using `Player#getSkin()`, as PlayerSkin.fromUsername calls a rate-limited API.
