### ISSUE TITLE
The repository is inactive, what next? Continuation of the project

### ISSUE THREAD

**Issue by Rollczi** [Minestom/Minestom#1983]
I don't know what's going on with minestom, but for people looking for a good fork, I recommend this: https://github.com/hollow-cube/minestom-ce

**Comment by GoldenStack** [comment]
I don't know if you're in the Minestom discord server, but Minestom-CE is maintained by Mattw, who works with base Minestom too.
Everyone already uses Minestom-CE, and it's going to get merged into base Minestom soon.

**Comment by mworzala** [comment]
#1937 is now merged.
