### ISSUE TITLE
Make Minestom independent of jitpack

### ISSUE THREAD

**Issue by MelonHell** [Minestom/Minestom#1987]
Related issue https://github.com/hollow-cube/minestom-ce/issues/118

If you do this, then Spark and LuckPerms may receive official Minestom support
https://github.com/LuckPerms/LuckPerms/pull/3521#issuecomment-1544551047

**Comment by ajh123** [comment]
Minestom is now on Maven central, so this issue can be closed I guess?

**Comment by MelonHell** [comment]
> Minestom is now on Maven central, so this issue can be closed I guess?

No, Minestom uses "hydrazine" library from jitpack

**Comment by ajh123** [comment]
Could you explain what hydrazine is used for?

**Comment by DasBabyPixel** [comment]
Pathfinding, see #1990

**Comment by MelonHell** [comment]
https://github.com/Minestom/Minestom/commit/5182f19dd7275073e54be5449f938fdedf2afcec
