### ISSUE TITLE
Open Deprecations

### ISSUE THREAD

**Issue by mworzala** [Minestom/Minestom#199]
Below is a table of the deprecated methods or groups of methods and roughly when they are planned for removal.

This Table does not cover all deprecations, and other methods may still be removed without warning, for example on Minecraft version updates, as the API is not yet stable..

None of these features should be used, since they will be removed at some point. If you are unsure about what to replace your usage of these deprecated features with, come and chat to us in the [Discord](https://discord.gg/rV24CzG).

| Deprecation                                                           | Reason            | Replacement                            | Removal        | See Also                                                                                                                                        |
|-----------------------------------------------------------------------|-------------------|----------------------------------------|----------------|-------------------------------------------------------------------------------------------------------------------------------------------------|
| Chat package (including `JsonMessage` and related methods/subclasses) | No longer needed  | Adventure API                          | Estimated 1.17 | https://wiki.minestom.com/feature/adventure                                                                                                     |
| `SoundCategory` enum                                                  | No longer needed  | Adventure API                          | Estimated 1.17 | https://wiki.minestom.com/feature/adventure#sound                                                                                               |
| Argument types `Long` and `Entities`                                  |                   |                                        | Estimated 1.17 |                                                                                                                                                 |
| `ResponseData#setName(String)`                                        | Misleading        | `#setVersion(String)`                  |                |                                                                                                                                                 |
| `ResponseDataConsumer`                                                | Replaced by event | ServerListPingEvent                    | 1.17           | [ServerListPingEvent](https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/event/server/ServerListPingEvent.java) |
| `ResponseData` methods for `Player` and `PingPlayer`                  | No longer needed  | `NamedAndIdentified` and entry methods | 1.17           |                                                                                                                                                 |
| `AdventureSerializer`                                                 | No longer needed  | The standard Adventure serializers     |                |                                                                                                                                                 |

**Comment by Geolykt** [comment]
I would mark them depreated for removal via the Deprecation annotation since we are already using Java 11

**Comment by mworzala** [comment]
They are, was mostly for us to keep track of what needs to be removed and when.

**Comment by Geolykt** [comment]
They aren't in master, if you are not understanding what I mean, I mean the `@Depreacted(forRemoval = true)` annotation

**Comment by mworzala** [comment]
> They aren't in master, if you are not understanding what I mean, I mean the `@Depreacted(forRemoval = true)` annotation

When you mark a deprecation `forRemoval`, IntelliJ will treat it as an error every time it is used, which is rather frustrating to work with unfortunately. 

Additionally, that doesn't say when it will actually be removed.

**Comment by KrystilizeNevaDies** [comment]
Closing as this is not being updated.
