### ISSUE TITLE
New system respecting player-view-distance not respecting view-distance changes

### ISSUE THREAD

**Issue by DasBabyPixel** [Minestom/Minestom#2066]
Create a dummy server, connect with view distance X<30 (12 good value), increase view distance by 3, see the effects.
![2024-03-29_13 25 17](https://github.com/Minestom/Minestom/assets/43410952/4c0e2ac0-8e04-47dd-a291-ba74fcd7b0c1)
New minecraft clients do not render chunks behind not fully loaded chunks. To get a better understanding Via + older MC version can demonstrate the problem very nicely.
![image](https://github.com/Minestom/Minestom/assets/43410952/3d0cedb3-75f2-4872-95c5-746eebb35692)
Red dot indicating where the view distance was increased (from 12 to 17 -> 5 chunk wide area gets never sent)

Related to #2051

**Comment by GreatWyrm** [comment]
I've opened a PR to fix this, it works on my end, would you mind confirming on your end as well?
