### ISSUE TITLE
Server doesn't stop correctly

### ISSUE THREAD

**Issue by Codestech1** [Minestom/Minestom#2096]
Minestom server doesn't stop correctly when using `MinecraftServer#stopCleanly`. Server's threads are still running.

I recorded a video showing the issue:
https://www.youtube.com/watch?v=QJkS8tqTKpA

**Comment by Codestech1** [comment]
I noticed that it happens only when at least one connection with player was made

**Comment by MelonHell** [comment]
We have exactly the same problem
