### ISSUE TITLE
Block spots while cancelling block place event.

### ISSUE THREAD

**Issue by RscerMC** [Minestom/Minestom#2103]
![a](https://github.com/Minestom/Minestom/assets/66514841/9236fb15-c88e-44ce-9c19-2003a391ad29)

```java
        globalEventHandler.addListener(PlayerBlockPlaceEvent.class, event -> {
            event.setCancelled(true);
        });
```

whenever i place a block sometimes it just leaves a black spot behind? Video explains it better.

**Comment by iam4722202468** [comment]
Can't reproduce this
