### ISSUE TITLE
`CommandSender#sendMessage` using a raw or MiniMessage message

### ISSUE THREAD

**Issue by mworzala** [Minestom/Minestom#212]
At the moment `sendMessage(String)` has been deprecated, however, it provides a useful debug option for easily sending a message to a player. 

Both raw sending and MiniMessage are valid options, we are looking for feedback.

**Comment by kezz** [comment]
I'm again adding minimessage, it's not nearly stable enough yet. However, undeprecating `#sendMessage(String)` and `#broadcastMessage(String)` is probably a good idea to allow for quick testing. Although the alternative of just statically important `Component.text` and doing `sendMessage(text(String))` seems fine to me..

**Comment by mworzala** [comment]
Solved by 59e67c0d827dcb9c4fa411454b9d22652f9bfb67
