### ISSUE TITLE
Not hiding itemstack tooltip

### ISSUE THREAD

**Issue by Z3koR** [Minestom/Minestom#2138]
I am trying to hide itemstack tooltip like this:
`val item = ItemStack.builder(Material.IRON_INGOT).set(ItemComponent.HIDE_TOOLTIP, null).build()`
`item.toItemNbt()` contains `minecraft:hide_tooltip` tag, but it seems that this component is lost when sending on client
The same problem with `HIDE_ADDITIONAL_TOOLTIP`

**Comment by GoldenStack** [comment]
Try setting `ItemComponent.HIDE_TOOLTIP` to `Unit.INSTANCE`, maybe it'll help - it works for me.

**Comment by Z3koR** [comment]
I am using kotlin and don't have field `INSTANCE`

**Comment by Z3koR** [comment]
By the way, due to the fact that `item.toItemNbt()` contains a tag. Maybe I didn't fully understand its structure, before the tag `minecraft:hide_tooltip` there is an `!`, maybe it means that it is not set.

**Comment by Z3koR** [comment]
That's right, you need to use `Unit.INSTANCE`. not kollin, minestom `Unit`.
