### ISSUE TITLE
No light calculation may be performed, in rare cases.

### ISSUE THREAD

**Issue by bea4dev** [Minestom/Minestom#2151]
When generating terrain, lights may not be calculated.
Checking the actual light level by using Instance#getSkyLight, it returns 0.
However, after the block is edited, it is computed normally and the notification is sent to the client as well.
![2024-05-26_15 05 29](https://github.com/Minestom/Minestom/assets/34712108/7ba33e32-9d1c-4811-b07b-433612c1c3a4)
![2024-05-26_15 25 14](https://github.com/Minestom/Minestom/assets/34712108/cebc1f5a-5232-4e5b-8fa7-75d7cf983495)

**Comment by iam4722202468** [comment]
What is the hash version you're using?

**Comment by bea4dev** [comment]
> What is the hash version you're using?

Latest version and "6b8a4e4".
I checked both.

Btw, this dark chunk appears to occur at the edge of the chunk rander area.
It has never been observed occurring in the center.

**Comment by bea4dev** [comment]
[Example code](https://github.com/bea4dev/MinestomChunkGenTest)

**Comment by iam4722202468** [comment]
Thanks, I can reproduce this

**Comment by bea4dev** [comment]
> Can you try [5035c2b](https://github.com/Minestom/Minestom/commit/5035c2b9e329d8d70a831dae14ae6d85de20a967)? I've implemented a fix.

It completely works. thanks!
