### ISSUE TITLE
DataComponents on 1.20.5 branch are completely broken

### ISSUE THREAD

**Issue by Flopgop** [Minestom/Minestom#2155]
# What's wrong
DataComponents are the new replacement for nbt and itemmeta and EXTREMELY IMPORTANT for everything item related

They don't work at all on the 1.20.5 branch

# Expected Behavior
add data component -> item on client appears as expected

# Actual Behavior
any data component on any item instantly crashes the client as soon as the packet is sent, client states "Caused by: java.lang.IllegalArgumentException: No value with id 56" after attempting to decode the set slot packet

# Steps to reproduce
join server
give player item with a data component
observe crash

# Minimal reproducer

```java
import net.kyori.adventure.text.Component;
import net.minestom.server.MinecraftServer;
import net.minestom.server.component.DataComponent;
import net.minestom.server.event.player.AsyncPlayerConfigurationEvent;
import net.minestom.server.event.player.PlayerSpawnEvent;
import net.minestom.server.instance.InstanceContainer;
import net.minestom.server.item.ItemStack;
import net.minestom.server.item.Material;
import net.minestom.server.network.NetworkBuffer;
import net.minestom.server.utils.nbt.BinaryTagSerializer;

public class Main {

    public static void main(String[] args) {
        MinecraftServer server = MinecraftServer.init();
        // Vanilla defined data component
        DataComponent<Component> CUSTOM_NAME = DataComponent.register("minecraft:custom_name", NetworkBuffer.JSON_COMPONENT, BinaryTagSerializer.JSON_COMPONENT); 
        // should be a netherite pickaxe with the name "BALLS"
        MinecraftServer.getGlobalEventHandler().addListener(PlayerSpawnEvent.class, e -> e.getPlayer().getInventory().addItemStack(ItemStack.builder(Material.NETHERITE_PICKAXE).set(CUSTOM_NAME, Component.text("BALLS")).build()));
        InstanceContainer container = MinecraftServer.getInstanceManager().createInstanceContainer();
        MinecraftServer.getGlobalEventHandler().addListener(AsyncPlayerConfigurationEvent.class, e -> e.setSpawningInstance(container));
        server.start("0.0.0.0", 25565);
    }
}
```

**Comment by LooFifteen** [comment]
You must use the existing `ItemComponent.CUSTOM_NAME`. Registering your own causes an increase in the component ID, which the vanilla client cannot expect.
![javaw_cElBPgLS0l](https://github.com/Minestom/Minestom/assets/39528861/abf32a14-8bef-4af6-8d4f-dc6e2c80fd3b)

**Comment by Flopgop** [comment]
I am going to kill someone, thanks.
