### ISSUE TITLE
Extending Item Class does not keep instance

### ISSUE THREAD

**Issue by Kyrotechnic** [Minestom/Minestom#2185]
Greeting, I know this is issue is very niche, especially since I modified minestom to try and achieve it. 

I have a class, "ClassA" that extends ItemStackImpl. My goal is to generate the DataComponentMap on packet sent specifically for the player.
So far, this has worked. I have been able to create an instance of "ClassA" and send it to the player and add it to their inventory.
However, the issue appears to be when I open my inventory on the client, the item turns from "ClassA" into ItemStackImpl, losing its super class. How does this work? Is there a way to fix this? I'm willing to modify code, I'm just perplexed that it's on inventory open, as there's not an event for that.

EDIT:

I also should clarify that it is still "ClassA" before the user opens their inventory. I added a check to test that. 

Thank you for reading

**Comment by mworzala** [comment]
This is not supported behavior, and will have a lot of issues. You should just set items per player and update the when necessary.

**Comment by Kyrotechnic** [comment]
> This is not supported behavior, and will have a lot of issues. You should just set items per player and update the when necessary.

I understand it is not supported behavior. I am curious about the server creating a new item instance on inventory close though.

**Comment by mworzala** [comment]
There are any number of places where a new instance can be created. Items are immutable so copied on every mutation, eliminating all of that and properly supporting a different case seems very complicated. If you want to see all of the cases where item stacks are instantiated you can comment out the constructor and see where errors pop up.

**Comment by Kyrotechnic** [comment]
Thank you for the idea. You're definitely right about it being complicated. The goal is to basically be able to generate it specifically from the player's view, so it relates to them, without having to scan and update too frequently.

**Comment by Kyrotechnic** [comment]
I fixed it, it appears to have been ItemStackImpl.with().
