### ISSUE TITLE
Why do we use Integer instead of boolean for chunk sections positions?

### ISSUE THREAD

**Issue by AntonIXO** [Minestom/Minestom#2207]
Minecraft left, Minestom right
![image](https://github.com/Minestom/Minestom/assets/25568560/e8cca9e0-62e9-4e76-b2ea-7ddb604ef365)
This is breaks [obj exporter](https://github.com/jmc2obj/j-mc-2-obj).

Is there any reason to keep it integer?

**Comment by GoldenStack** [comment]
NBT doesn't support booleans. I assume you mean Byte

**Comment by mworzala** [comment]
Sounds like a bug, if Minecraft is using a byte we should also

**Comment by AntonIXO** [comment]
> NBT doesn't explicitly support booleans. I assume you mean Byte

Byte of course. Confused a bit.)
