### ISSUE TITLE
Feature: API to store arbitrary data on entities (server-side metadata)

### ISSUE THREAD

**Issue by Steanky** [Minestom/Minestom#2208]
Such a feature would allow you to store any object on an `Entity`. With a bit of effort it could be made type-safe. The implementation would be a simple wrapper around a Map. 

At first glance, this feature sounds similar to the existing `Tag` API. However, there are a few key differences:

* Tags are limited in the types of data they can store
* Tags are designed to be interoperable with NBT, whereas my proposal would specify no such requirement

The use case for this feature is, I think, fairly common: you have an entity, and you want to associate some object with it that can't be directly represented as a tag, such as a reference to the game the entity is in. 

It's currently possible to accomplish the same effect with a few methods, but they all have notable drawbacks:

* You can store a`Tag<String>` or `Tag<UUID>` and use that to look up the object you wish, but this is error-prone, less performant, and adds a cumbersome layer of indirection
* You can maintain a `Map<UUID, (your-metadata-type)>` with the key as the entity's UUID, but this requires you to ensure that the metadata objects don't outlive the entities (memory leak potential)
* You can extend Entity and add whatever custom fields you need, but this won't allow server-side metadata to be defined at runtime, is cumbersome, and a non-starter if you need the API to exist for all Entity subclasses

If this feature sounds desirable, I would be happy to implement it and make a pull request!

**Comment by mudkipdev** [comment]
This can be done with a transient tag. ```java
public static final Tag<CustomObject> CUSTOM = Tag.Transient("custom");
```

**Comment by Steanky** [comment]
> This can be done by setting the tag as transient. (a shortcut for defining it with no serializer)
> 
> ```java
> // Can be used with any data type but cannot be saved
> public static final Tag<CustomObject> CUSTOM = Tag.Transient("custom");
> ```

Thanks! Can't use this on my fork as it's out of date, but didn't know this existed on the modern API.
