### ISSUE TITLE
Teleport confirmation issue

### ISSUE THREAD

**Issue by MelonHell** [Minestom/Minestom#2220]
On our server there is weapon recoil, which moves the player's camera with relative teleports. While shooting, the player model will often suddenly "teleport" as some movements are ignored

The problem is in these lines
https://github.com/Minestom/Minestom/blob/d5c6126a6b8260dfc06033dc08bf6603bb8f1b57/src/main/java/net/minestom/server/listener/PlayerPositionListener.java#L47-L49

If you disable the teleport confirmation system (that is, simply delete these lines), this will greatly aggravate the [problem of falling through the world #2017](https://github.com/Minestom/Minestom/issues/2017)

**Comment by DeidaraMC** [comment]
This system is in place to prevent players from moving around visibly after being teleported until their clients get the information. It's the whole reason the client sends a teleport acknowledgement packet back. For your case there's also a lookat packet which sets the players yaw/pitch without needing a confirmation

**Comment by MelonHell** [comment]
I don't think this solves the problem

**Comment by MelonHell** [comment]
Firstly, I will have to use reflection to force the yaw and pitch values, since this is not provided in the API. Secondly, this package does not use yaw and pitch, which means you will have to do a conversion. Thirdly, I think this is an incorrect use of teleportation confirmation, I think other problems may arise from this

**Comment by MelonHell** [comment]
Now I have written such a fix, maybe something like this can be built into Minestom
https://github.com/SkolkovoLab/Minestom/commit/d132627c3d8fe624fc52fd5737741c7b1c3fa417
