### ISSUE TITLE
jmc2obj export broken

### ISSUE THREAD

**Issue by AntonIXO** [Minestom/Minestom#2223]
Getting such spam when saving world. Worked fine with 19bb74e942.
Possibly thats breaks [jmc2obj](https://github.com/jmc2obj/j-mc-2-obj) export
Logs uploaded to Github gist because looked awful directly in issue: https://gist.github.com/AntonIXO/778160b27ce3884b549429280e5e0130

**Comment by QuadrixYT** [comment]
I got the same error but in 1.21, any idea how to fix

**Comment by AntonIXO** [comment]
> I got the same error but in 1.21, any idea how to fix

[jmc2obj author won't fix.](https://github.com/jmc2obj/j-mc-2-obj/issues/262#issuecomment-2223412953)

This should be fixed on minestom side.

But export works fine on 19bb74e942 commit. Before new anvil code.

**Comment by QuadrixYT** [comment]
Fix for me was to load the world in single player kill all entities and then load it on minestom, so its just entities which cant get loaded
