### ISSUE TITLE
AttributeInstance addModifier unintuitive behavior

### ISSUE THREAD

**Issue by mworzala** [Minestom/Minestom#2225]
Currently when using `AttributeInstance#addModifier` the modifier will use a `putIfAbsent` call to add the modifier, meaning that it will not overwrite a previous value. To me this was unintuitive where I would have expected a new addModifier call to overwrite the previous value.

Just want to check I am not the only one who reads this as unintuitive behavior.

**Comment by Steanky** [comment]
Also seemed a bit weird to me. If it's changed, I think  that `addModifier` will also (sometimes) have to re-compute the cached value (unless the replaced modifier is identical to the new one).
