### ISSUE TITLE
feat: Add some way to get component bounding boxes of a Shape

### ISSUE THREAD

**Issue by Steanky** [Minestom/Minestom#2239]
Currently, there is no way to access the collision bounding boxes that (may) make up a `Shape`; as in the case of stairs, there could be more than one.

Exposing this would be useful for third-party pathfinding solutions, that want to perform their own minimal collision checks, rather than using `intersectBoxSwept` or similar methods.

I'm not necessarily proposing a change to the `Shape` interface -- since that seems to have no concept of "child" bounding boxes, only providing some collision primitives -- but at least `ShapeImpl` should provide a way to view its `collisionBoundingBoxes` field.

**Comment by Sternig** [comment]
yes

**Comment by Exponentiating** [comment]
I agree strongly!

**Comment by derKaempferHD** [comment]
Yep, this would make life easier for Steanky for sure

**Comment by MelonHell** [comment]
finally someone raised this issue instead of silently using reflection :D
