### ISSUE TITLE
Packets 0x1E and 0x1F are wrong inside the current version of Minestom

### ISSUE THREAD

**Issue by jglrxavpok** [Minestom/Minestom#224]
See title.

Packets 0x1E and 0x1F are wrong inside the current version of Minestom (see ClientRecipeBookData) https://wiki.vg/Protocol#Set_Recipe_Book_State

ClientRecipeBookData should be split into two different packets instead of relying on the 'type' field.

**Comment by TheMode** [comment]
Fixed with 63159cc49a73ed33774cb4e8ed8e0577322eaf51
