### ISSUE TITLE
Can't play sound to player

### ISSUE THREAD

**Issue by AsuDev2** [Minestom/Minestom#233]
```JAVA
public static void playSound(Player player, String sound, String source, float volume, float pitch) {
    player.playSound(Sound.sound(Key.key(sound), Sound.Source.valueOf(source), volume, pitch));
}    
````
Does not work and throws a IllegalArgumentException. It says "Sound must be a valid sound event". This method is just the ```playSound(Sound sound)``` method. The one that has ```playSound(sound, x, y, z)``` does work however. I am not entirely sure how it does not work but it is an issue that should be fixed.

**Comment by kezz** [comment]
So this exception happens because playing a sound without a location uses the EntitySoundEffectPacket which must take a vanilla sound event. This method could be changed to send the entity sound effect packet if the sound event exists and otherwise fallback to the normal sound effect packet with the coords of the player. Would be interested to hear others thoughts on this.

**Comment by kezz** [comment]
Just an update on this, other implementations use `#playSound(Sound)` as an overload for the location specific method `'#playSound(Sound, double, double, double)`. I'm still not sure this is correct, as to me if you're playing a sound it should follow the location of the source if the source has not been specified.

There is an Adventure PR open at the moment that adds a method that will enable developers to write something like `player.playSound(sound, player)` but this isn't a great method to use as it wouldn't be easy to say "play a sound following the player for this group of players". We could alternatively add something along the lines of `player.playSound(Sound, Audience)` or have some overloaded boolean method to follow the members but I'm not a massive fan of this either.

**Comment by kezz** [comment]
Blocked on https://github.com/KyoriPowered/adventure/pull/330 and https://github.com/KyoriPowered/adventure/pull/316.
