### ISSUE TITLE
Weird hardcoded item pickup cooldown for LivingEntity with no option to overwrite it

### ISSUE THREAD

**Issue by Soupertonic** [Minestom/Minestom#2351]
I was playing around with the Minestom API and noticed that there is a weird item pickup cooldown that cannot be overwritten e.g. `entity.setItemPickupCooldown()`. What is the reason for the item pickup cooldown?

The cooldown: https://github.com/Minestom/Minestom/blob/a521c4e7cd1971f95fc7280fc986f663073b18ac/src/main/java/net/minestom/server/entity/LivingEntity.java#L60
Used here: https://github.com/Minestom/Minestom/blob/a521c4e7cd1971f95fc7280fc986f663073b18ac/src/main/java/net/minestom/server/entity/LivingEntity.java#L196
Here's a video demonstrating what I'm talking about: https://www.youtube.com/watch?v=LXW2AjTglzM

**Comment by mworzala** [comment]
Its just a default, you can reassign the time by setting the field.
