### ISSUE TITLE
Implementing custom items/blocks?

### ISSUE THREAD

**Issue by NullableIsBellable** [Minestom/Minestom#2369]
Can you add custom items or blocks? or is it like a datapack or spigot plugin where you have to use custom model data or CIT(requires the player to have either optifine or CIT resewn or smth similar installed) using custom model data wont work with blocks though as just simply placing the block and picking it back up will get rid of your custom model data and how do I push a resource pack for the player when they join

**Comment by TheMode** [comment]
This is not the right place for questions, use the discussions page https://github.com/Minestom/Minestom/discussions
or join our discord.

To quickly answer, minestom is server-side only and therefore share roughly the same solutions as spigot.
