### ISSUE TITLE
Items disappear in inventory when drag clicking

### ISSUE THREAD

**Issue by kezz** [Minestom/Minestom#240]
As can be seen in the following video, holding an item in your cursor and spam left-clicking whilst moving the item causes items in the inventory to disappear.

https://user-images.githubusercontent.com/1526243/114378516-b08b4080-9b7f-11eb-9654-1d0204081aea.mp4

**Comment by TheMode** [comment]
Fixed by 25311619645951c24583095628bd93a31bd398b3
