### ISSUE TITLE
JLine auto-completion/suggestion

### ISSUE THREAD

**Issue by TheMode** [Minestom/Minestom#241]
Integrate JLine more closely with our current command framework, perhaps even with dynamic suggestion options accessible from `Argument` (eg: file suggestion)

**Comment by kezz** [comment]
For reference, these two patches are how Paper handle better terminal support: 
- https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0146-Use-TerminalConsoleAppender-for-console-improvements.patch
- https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0701-Enhance-console-tab-completions-for-brigadier-comman.patch

**Comment by mworzala** [comment]
Terminal is deleted for now, this will be relevant if we end up with an external library for this.
