### ISSUE TITLE
Trim material registry asset name is incorrect

### ISSUE THREAD

**Issue by lordtgm** [Minestom/Minestom#2425]
based on [Registry Data - wiki.vg](https://wiki.vg/Registry_Data#Armor_Trim_Material), asset_name is a namespace. however in Minestom, the namespace lacks the first part ("diamond" instead of "minecraft:diamond", for example)
![image](https://github.com/user-attachments/assets/55622320-9213-4cee-9fe6-2984d9e683de)

**Comment by mworzala** [comment]
wiki.vg is wrong. The asset name specifically cannot include a namespace. The client validates this structure using `Codecs.IDENTIFIER_PATH` which only allows path characters (notably not `:`). The namespace used for the material asset is the namespace of the path. You can check `net.minecraft.item.trim.ArmorTrim` (Yarn mappings) for the associated logic to get the asset, or `net.minecraft.item.trim.ArmorTrimMaterial` (also Yarn mappings) for the Codec used to deserialize this registry.
