### ISSUE TITLE
Multi-part entities

### ISSUE THREAD

**Issue by ChrisMcLain** [Minestom/Minestom#247]
We would like to support entities made from multiple armor stands. This way, it's a standard, optimized feature, and not everyone will have to reinvent the wheel to add it to their projects.

My suggestion for implementing this is to follow the example that the Spigot plugin [Model Engine](https://www.spigotmc.org/resources/conxeptworks-model-engine%E2%80%94ultimate-entity-model-manager-1-14-1-16-5.79477/) has set for us. Their wiki articles document how they expect models and animations to be set up in BlockBench. This includes special markers such as `h_` for the head which swivels separately from the body, `hitbox` for custom hitboxes, etc. Then, the tool reads in BlockBench files, generates the necessary resource pack, and creates the entity in game using ArmorStands. 

This is obviously a complex endeavor, so a proposal for a simpler approach would be welcomed :)

It would also be cool for these entities to support the same AI system and all of the other Entity features Minestom has right out of the box. I.e., they extend from `LivingEntity` or something similar, and all the magic happens behind the curtain.

As another user noted, we could also support higher framerates than 20fps. Perhaps there could be a way to set a framerate based on distance.

**Comment by Zanctarian** [comment]
In a month from now, I'd be willing to look into adding support for BlockBench files. As for the hitbox, Minestom currently doesn't have a way to do custom hitboxes.. but I'd also be willing to look into adding that as well.

If anyone else wants to take this on before I do, go ahead! It'll be a while until I look into it.

**Comment by Eoghanmc22** [comment]
BlockBench uses .bbmodel (just json) to store data. The bbmodel file contains everything including the geometry, animations, and textures (base64 encoded png). This shouldn't be included in the main repo. I think this should be split into 2 extensions. One that manages dynamic resource pack creation from the format the client expects and also has the ability to generate the json files the client expects. Should be easy enough to do with gson. It would also manage mapping textures/models to block states and custom model ids. This would be a way for all Minestom implementations and extensions to generate resource packs and would prevent conflicting implementations of similar features. Might be good to wait till the data generator tho. The other extension would depend on the first and read block bench files, create the entities, play the animations and whatever else is needed.

**Comment by TheMode** [comment]
I agree that it should not be part of the main module. Though I would really like to integrate something like this into the project, could be used for even more than just entities.

**Comment by iam4722202468** [comment]
[This](https://github.com/AtlasEngineCa/WorldSeedEntityEngine/tree/master) Library can do what you're suggesting
