### ISSUE TITLE
Make Entity class as an interface, and rename existing implementation to AbstractEntity

### ISSUE THREAD

**Issue by DefinitlyEvil** [Minestom/Minestom#248]
Hello, 
  Is it possible to make Entity class as an interface? And rename existing imeplementation to AbstractEntity? 

Thanks,
Tobias.

**Comment by Geolykt** [comment]
What would the motivation be behind that?

**Comment by TheMode** [comment]
If your goal is to modify some parts of the current class you might be interested by Mixin https://wiki.minestom.com/expansion/mixin-support

What would be your use case?

**Comment by DefinitlyEvil** [comment]
Hello @Geolykt and @TheMode , 
Thanks for the reply, I'm trying to make a distributed server using Java RMI. For example I can make `RemoteEntity` and `RemoteChunk`.

**Comment by mworzala** [comment]
its very performant, everything happens on class load. After load there is no difference than if it was done in the source (besides a lack of compiler optimization).

Also, I am pretty sure you could use mixins to accomplish what you want. You can use them to make a class inherit from other interfaces.

**Comment by DefinitlyEvil** [comment]
@mworzala Thanks for the response, after some readings about Mixins I found they are very flexible!

**Comment by mworzala** [comment]
You can cast the `Chunk` to `IChunk` anywhere you need it

**Comment by DefinitlyEvil** [comment]
@mworzala Yes I know, but in `Instance` or `InstanceContainer` they have to use `IChunk` instead of just `Chunk`. Is there a way to use mixins to change member variable signature?

**Comment by mworzala** [comment]
Why does the signature matter?

**Comment by DefinitlyEvil** [comment]
@mworzala My idea was to make two types of `IChunk`, one is locally hosted `Chunk` (normal ones) and remote chunks on other hosts `RemoteChunk`, so `Instance` or `InstanceContainer` should be able to store both types. I'm very new to Mixins maybe I can do that in another approach?

**Comment by mworzala** [comment]
So you just need to add a property on the remote side if I'm understanding correctly? If thats the case, properties can be added by mixins. Perhaps I don't understand though.

**Comment by DefinitlyEvil** [comment]
Oh, I just discovered that only `InstanceContainer` used `Chunk`, not `Instance`. Maybe I can implementa new `DistributedInstance` and use `IChunk` as interface... xD

**Comment by TheMode** [comment]
Chunk is already an abstract class with not much logic inside, couldn’t you just have IChunk extends it?

**Comment by DefinitlyEvil** [comment]
@TheMode I think I'll try... By the way is there a convinient way to load MCA regions?

**Comment by mworzala** [comment]
Minestom doesn't currently load anvil worlds on its own. There is an anvil loader in vanilla reimplementation here: https://github.com/Minestom/VanillaReimplementation/blob/master/src/main/java/net/minestom/vanilla/anvil/AnvilChunkLoader.java

**Comment by DefinitlyEvil** [comment]
@mworzala Woah! That's amazing, sorry I missed it. xD
