### ISSUE TITLE
Split click types for dragging into multiple for different mouse buttons

### ISSUE THREAD

**Issue by stefvanschie** [Minestom/Minestom#250]
Currently `ClickType.START_DRAGGING` and `ClickType.DRAGGING` are the only two click types related to dragging in an inventory. From these it's not clear which mouse button was used for the dragging (i.e., left mouse button, right mouse button or middle mouse button). The suggestion is to split up these two click types into multiple ones for each mouse button, similar to how there is a `ClickType.LEFT_CLICK` and a `ClickType.RIGHT_CLICK`. For example, `ClickType.START_LEFT_DRAGGING`, `ClickType.LEFT_DRAGGING`, `ClickType.START_RIGHT_DRAGGING`, `ClickType.RIGHT_DRAGGING`, `ClickType.START_MIDDLE_DRAGGING`, `ClickType.MIDDLE_DRAGGING`. This way servers and extensions can easily identify which type of dragging has or is occurring and respond appropriately to each one.

**Comment by lexikiq** [comment]
I believe this issue is fixed

**Comment by TheMode** [comment]
Indeed, closing.
