### ISSUE TITLE
ItemEntity is very buggy

### ISSUE THREAD

**Issue by vearen1** [Minestom/Minestom#2521]
`ItemEntity` is very buggy; it moves all over the place and bounces when landing on the ground.

https://github.com/user-attachments/assets/2d711c44-2bff-4b21-bebf-fa3ce8b23ac8

https://github.com/user-attachments/assets/3dedeeaf-1838-4011-9859-492f6473f995

**Comment by mworzala** [comment]
Fixed by #2544
