### ISSUE TITLE
PlayerBlockPlaceEvent does not cancel on event.setCancelled(true) in conjunction with nearby changes

### ISSUE THREAD

**Issue by HyperKids** [Minestom/Minestom#254]
**Description:** PlayerBlockPlaceEvent does not cancel as expected
**Expected Behavior:** Block should not be placed
**Actual Behavior:** Block is placed, and persists
**Code used for testing:**
```java
GlobalEventHandler globalEventHandler = MinecraftServer.getGlobalEventHandler();
globalEventHandler.addEventCallback(PlayerBlockPlaceEvent.class, event -> {
    event.setCancelled(true);
});
```

**Comment by HyperKids** [comment]
Testing further, it seems like there are a very specific set of conditions that need to be fulfilled - I'll update with more details in a moment.

**Comment by HyperKids** [comment]
Here is the minimum code necessary to reproduce the error. This was created as an extension. The real issue is likely the block underneath the cancelled block being changed immediately on the same tick / beforehand.

**MinestomExtensionTest.java**
```java
public class MinestomExtensionTest extends Extension {
    @Override
    public void initialize() {
        new CanvasEventHandler();
    }

    @Override
    public void terminate() {

    }
}
```

**CanvasEventHandler.java**
```java
public class CanvasEventHandler {
    public CanvasEventHandler() {
        GlobalEventHandler globalEventHandler = MinecraftServer.getGlobalEventHandler();
        globalEventHandler.addEventCallback(PlayerHandAnimationEvent.class, event -> {
            handleCanvasEvent(event.getPlayer(), getTarget(event.getPlayer(), 5));
        });
        globalEventHandler.addEventCallback(PlayerBlockPlaceEvent.class, event -> {
            event.setCancelled(true);
        });
    }

    public final BlockPosition getTarget(Player player, Integer range) {
        BlockIterator bi = new BlockIterator(player, range);
        BlockPosition lastBlockPos = bi.next();
        while (bi.hasNext()) {
            lastBlockPos = bi.next();
            Block lastBlock = player.getInstance().getBlock(lastBlockPos);
            if (lastBlock.isAir())
                continue;
            break;
        }
        return lastBlockPos;
    }

    private boolean handleCanvasEvent(Player player, BlockPosition blockpos) {
        player.getInstance().setBlock(blockpos, player.getItemInMainHand().getMaterial().getBlock());
        return true;
    }
}
```

**Comment by HyperKids** [comment]
Gif for your convenience. Uses the above code.
![minestom-issue-254](https://user-images.githubusercontent.com/12666237/115651308-c1565780-a2df-11eb-8c73-574fec31fb82.gif)

**Comment by TheMode** [comment]
I am for the moment unable to reproduce https://cdn.discordapp.com/attachments/786079397110874135/834692658827755530/Screen_Recording_2021-04-22_at_09.30.11.mov

**Comment by Kebab11noel** [comment]
It could be a syncronization issue (try re-joining), there is a [comment I wrote explaining a similar edge case](https://github.com/Minestom/Minestom/blob/135ecf7b9c300168d6d356a66fb1befc78af8107/src/main/java/net/minestom/server/listener/BlockPlacementListener.java#L100-L102) and it looks like cancellation still handled the "old" way.

**Comment by HyperKids** [comment]
Blocks are indeed client sided, rejoining removed them. Without the PlayerHandAnimationEvent (that triggers the block change underneath the one placed), this issue isn't present - might have to do with the chunk refreshing from the triggered block change at the same time that air (for the client-side refresh) is attempted to be placed.

**Comment by Kebab11noel** [comment]
Just tried to reproduce (to attempt the fix), but I couldn't reproduce it either, are you on the latest commit? Maybe it got already fixed.

**Comment by TheMode** [comment]
May want to open a new issue based on `new-block-api` latest. For now we cannot reproduce.
