### ISSUE TITLE
Less generic name for Instance

### ISSUE THREAD

**Issue by xt449** [Minestom/Minestom#314]
The naming for Instance object and those relating to it is ridiculous.
There a field for DimensionType yet the programmer has not been informed of any Dimension objects. There is also a WorldBorder field; so clearly the names here are not consistant.

To help those coming from other APIs we could use World or more accurately WorldContainer, similarly Dimension or DimensionContainer, or to accommodate the abstractness that is this class it could simply be a Region.

Whatever is chosen, please don't use the most vague possible class name.

**Comment by xt449** [comment]
What about World? Is there some fundamental difference for why this name has not been used?

**Comment by TheMode** [comment]
I feel that World could also become confusing.
To give a simple example, let's say you have a single map but divided into 5 to dispatch players (often seen in MMORPG). Would you say that there are 5 worlds or instances?

Not saying that our naming is perfect, we can still take feedback

**Comment by xt449** [comment]
Although, Minestom doesn't use regions or the region file format so that seems to be a decent name. But since it is already defined as something else in the Minecraft community, I can understand that too.

How about RegionContainer? This would be troublesome with the current InstanceContainer, so its still not ideal, but getting there.

I think ***Universe*** has potential though since it does not have any other name conflicts.

**Comment by xt449** [comment]
The name that Mojang uses (Level) is also available, albeit worse than Dimension.
Could also use Realm, but it is already a Minecraft term so I can understand not wanting to try that.

However, the more I've been thinking, World is just such a easy name, even if it's not a perfect description it fits well enough and has the bonus of being recognizable by developers from other Minecraft modding APIs

**Comment by xt449** [comment]
Not sure if this is close enough on topic, but why is the block package inside the instance package?

**Comment by xt449** [comment]
@TheMode how about Zone? That's what you mean by instance right?
I can't find a meaning or similar word that makes sense for instance, https://www.merriam-webster.com/dictionary/instance

**Comment by TheMode** [comment]
instance, world, level, dimension, universe, space, zone

There are a lot of possible names but I do not think that we should focus on it. There are a lot of more important issues

**Comment by xt449** [comment]
Okay

**Comment by xt449** [comment]
I'll go work on those then
