### ISSUE TITLE
Any plans on implementing support for bukkitAPI?

### ISSUE THREAD

**Issue by NiceCraftz** [Minestom/Minestom#339]
title, sorry for using the issue section.

**Comment by NiceCraftz** [comment]
no need to harass for this, lmao

**Comment by TheMode** [comment]
I personally do not hate the bukkit API, but I would say that this is very low priority and is unlikely to work great:

1. We do not have parity with mojang implementation
2. NMS is also an issue (see Glowstone)

**Comment by kezz** [comment]
See https://github.com/Project-Cepi/Bukstom
