### ISSUE TITLE
Death screen from void damage does not show player name

### ISSUE THREAD

**Issue by TwoLeggedCat** [Minestom/Minestom#369]
When using a "default" server as from [here](https://wiki.minestom.com/setup/your-first-server), if a player falls into the void, they are presented with a death screen that simply states "fell into the void." In the chat, however, the correct message, "Username fell into the void" is displayed. I wasn't sure if this constituted a bug or if it was up to the developers using Minestom to handle, but I was told to report it, so here we are.

**Comment by mworzala** [comment]
Void damage is not done by Minestom anymore as of #1937
