### ISSUE TITLE
Ghost Items

### ISSUE THREAD

**Issue by R0bbyYT** [Minestom/Minestom#37]
### What is the current behavior?
If you change the slot of the hotbar quickly, ghost items occur.
### What is the expected behavior?
No ghost items when you scrolling through the hotbar quickly.
### What steps will reproduce the problem?
1.	Join the server
2.	Sets the gamemode to survival
3.	Scroll through the hotbar with the mouse wheel (fast)
#### Operating System:
    Edition: Windows 10 Home
    Version: 1909
    Operating system build: 18363.959
#### Java:
    openjdk 14.0.1 2020-04-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
### Additional information / Possible thoughts on why this bug is happening
I think the server sends one packet too many when scrolling the hotbar.

**Comment by TheMode** [comment]
Should be fixed in the last commit

**Comment by R0bbyYT** [comment]
Yes it was fixed!
