### ISSUE TITLE
Water disappearing when blocks placed adjacent to water

### ISSUE THREAD

**Issue by AwesomestCode** [Minestom/Minestom#392]
## Description
When a player places a block next to a previously placed water source block, the water disappears.

## Steps to Reproduce
1. Go into creative mode
2. Place a water block anywhere in the world.
3. Walk one block to the side of the water block (the player's feet should be at the same y-level as the water)
4. Look directly down and place a stone block. The block doesn't place (intended, because the player is occupying the position where the block would go). However, the water now disappears, even though you never touched the water block when placing the stone.

## Tested Versions
- I tested this on 5b726f91c but it likely affects other versions too because that PR doesn't touch this aspect at all.

**Comment by Marlonzockt** [comment]
The real issue isn't that the water disappears, it actually is never present on the server in the first place, since buckets are not implemented. The client just assumes it can place water and the server doesn't correct it until you update it (which you do in your steps)
