### ISSUE TITLE
Packet & buffer revamp

### ISSUE THREAD

**Issue by TheMode** [Minestom/Minestom#396]
* Make all packets `record`, perhaps with a single class for all client and another for server packets
* Replace BinaryWriter/Reader with `BinaryBuffer` in preparation for https://openjdk.java.net/jeps/412, and to use a single buffer class across the codebase
* Make packets convertible to string for debugging purpose (perhaps no deserialization)

**Comment by mworzala** [comment]
This has all been done I believe
