### ISSUE TITLE
Multiple InventoryPreClickEvents firing when moving an item

### ISSUE THREAD

**Issue by ZakShearman** [Minestom/Minestom#403]
When a player has their inventory open and moves an item by pressing a number on their hotbar, InventoryPreClickEvent is fired twice. Once has the correct slot and the second has a seemingly random slot.

In this example, the item is moved from minestom slot 1 to 9 (by pressing 2 on the keyboard), but another `InventoryPreClickEvent` is fired with slot 37.

https://user-images.githubusercontent.com/34372536/128965614-5e9ab0cc-3397-48cb-a8c4-45527234199d.mp4

Just for people to understand, these are the minestom slot numbers:
![Pessimistic-Gallowaycow-12705](https://zak.pink/2021/08/Pessimistic-Gallowaycow-12705.png)

**Comment by TheMode** [comment]
Fixed by 5607652378f8845e74085c33e9849310430df663
