### ISSUE TITLE
Logger behavior in shutdown tasks

### ISSUE THREAD

**Issue by RinesThaix** [Minestom/Minestom#432]
![image](https://user-images.githubusercontent.com/3867723/130836023-fefc9299-6d26-4a27-97b8-e2bf30ff27af.png)
With such code my output on server shutdown looks like:
```
[Thread-1] [20:15:03] (MinecraftServer.stopCleanly) - INFO - Stopping Minestom server.
[Thread-1] [20:15:03] (SchedulerManager.shutdown) - INFO - Executing all shutdown tasks..
bye
```
Sometimes it also catches first `info()` from that code-snippet.
It seems that logger (or maybe it's output to console?) is being disabled somewhere in parallel with the execution of shutdown tasks.

**Comment by BomBardyGamer** [comment]
The log manager is disabled via a shutdown hook. There is no way that you can guarantee the order that shutdown hooks will be executed when the server is shut down. The solution I think would be most fitting is to disable the shutdown hook in the Log4J 2 configuration and manually shut down Log4J 2 when the server is shut down. This way, you can guarantee when Log4J 2 is going to be shut down.

**Comment by Articdive** [comment]
Since we don't use LOG4J2 I believe this ticket is no longer of relevance.
Please reopen if you disagree.
