### ISSUE TITLE
Writable book shows raw json

### ISSUE THREAD

**Issue by EpicPlayerA10** [Minestom/Minestom#473]
Writable book shows raw json instead of readable text.
Screenshot:
![image](https://user-images.githubusercontent.com/62206933/135484298-058888b4-5dda-42a7-af74-24ce781a1c0c.png)
Code:
```java
ItemStack book = ItemStack.of(Material.WRITABLE_BOOK).withMeta(builder -> {
    WritableBookMeta.Builder bookMetaBuilder = (WritableBookMeta.Builder) builder;
    bookMetaBuilder.pages(Arrays.asList(Component.text("Hi there"), Component.text("test")));
    return bookMetaBuilder;
});
```

**Comment by yusshu** [comment]
I think writable books do not support components, try using a written book
https://minecraft.fandom.com/wiki/Written_Book
https://minecraft.fandom.com/wiki/Book_and_Quill (Writable book)

Also I think you can use [Player#openBook](https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/entity/Player.java#L731), see [Adventure Books](https://docs.adventure.kyori.net/book#constructing-a-book)

**Comment by EpicPlayerA10** [comment]
I can use written book but this is still a bug

**Comment by yusshu** [comment]
> > I think writable books do not support components, try using a written book https://minecraft.fandom.com/wiki/Written_Book https://minecraft.fandom.com/wiki/Book_and_Quill (Writable book)
> 
> I can use written book but this is still a bug

Ah yes, I think the bug is [here](https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/item/metadata/WritableBookMeta.java#L73)
