### ISSUE TITLE
Mods support

### ISSUE THREAD

**Issue by leonardo-dgs** [Minestom/Minestom#484]
I don't know if it is possible, but Minestom can be made compatibile with mods?
In that case, in which way should work handling mods on server side?

**Comment by Geolykt** [comment]
I have been so far been unable to get forge compat but fabric compat is more easily doable because it's just "connect and pray" more or less

**Comment by KrystilizeNevaDies** [comment]
> I have so far been unable to get forge compat but fabric compat is more easily doable because it's just "connect and pray" more or less

How is fabric compat more doable? Don't fabric mods heavily rely on vanilla code? Its almost all mixins afaik.
