### ISSUE TITLE
Economy API

### ISSUE THREAD

**Issue by Leonardo-DGS** [Minestom/Minestom#512]
I'm not sure if it is suited, but it would be useful an Economy API like the Sponge one.

**Comment by BomBardyGamer** [comment]
I believe that this isn't really that necessary. Whilst the idea of the Sponge API is great, and why Sponge have created it, which is to avoid plugins like Vault appearing, I do not believe that it fits within Minestom, as it is mainly aimed at people who wish to use it as a library to build their own Minecraft server, and this target doesn't need this sort of API, as most would use their own economy system built-in to their server software, which they will just interface with directly themselves.

**Comment by Leonardo-DGS** [comment]
So maybe should be done as third-part library, if you want to use a public economy extension and not a custom one?

**Comment by KrystilizeNevaDies** [comment]
This feature does not correctly fit within Minestom core. It is a better idea for a library.
