### ISSUE TITLE
Placeholder API

### ISSUE THREAD

**Issue by Leonardo-DGS** [Minestom/Minestom#513]
It would be useful a Placeholder API, like the Sponge one, not implementing the parser, where you can register placeholders.

**Comment by BomBardyGamer** [comment]
PlaceholderAPI 3 is currently in development, which is cross-platform, and will support multiple platforms. It is currently private, however, it will be publicised when it is ready for release. If you wish to join the development process, and want to suggest that Minestom support is added, you can join the [HelpChat](https://discord.gg/helpchat) Discord and ask the admin `PiggyPiglet` (his avatar is a pig, you won't miss him), then he may allow you access to the repository.

**Comment by KrystilizeNevaDies** [comment]
This feature does not correctly fit within Minestom core. It is a better idea for a library.
