### ISSUE TITLE
Ban API

### ISSUE THREAD

**Issue by Leonardo-DGS** [Minestom/Minestom#514]
A Ban API, obviously not implementing the bans.
Rather an abstraction layer that allows extensions to register bans, so that other extensions can check if a player is banned without knowing the extension that implements the Ban API.

**Comment by LeoDog896** [comment]
Definitely not, a ban layer should only be implemented by extensions and not the server. Most servers handle banning on the proxy level.

**Comment by LeoDog896** [comment]
Instead, these should have a community-official extension

**Comment by Leonardo-DGS** [comment]
I meant an API, not implementing itself the bans, you are not obliged to use it.
This API prevent extensions to check every API of every ban extension.
Making a third part API for this, a plugin developer would have to choose what API to use.

**Comment by KrystilizeNevaDies** [comment]
`a plugin developer would have to choose what API to use`

I believe that this is a good thing in this case, it means that if ever another better bans extension comes along, then individuals can move to it with no issues. E.g. the PEX -> LuckPerms swap that happened for permissions in spigot.

**Comment by Leonardo-DGS** [comment]
Indeed, you can switch from PEX to LuckPerms with no issues because there is the Player#hasPermission method directly in Bukkit, and it's not needed to use the PEX or LuckPerms API.
The Ban API would allow to do similar things without implementing the ban system.

**Comment by BomBardyGamer** [comment]
This poses a similar issue to what I said for the Economy API, where it is unnecessary for most people that will be using it. Also, something I failed to address in my comment on the Economy API is the fact of how people would provide their own ban services.

**Comment by KrystilizeNevaDies** [comment]
This feature does not correctly fit within Minestom core. It is a better idea for a library.
