### ISSUE TITLE
Using with maven

### ISSUE THREAD

**Issue by SJS830** [Minestom/Minestom#52]
Hi, I am unable to use this as a dependency in my maven project.

Here is the relevant part of my pom.xml:
```
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.Minestom</groupId>
            <artifactId>Minestom</artifactId>
            <version>master-SNAPSHOT</version>
        </dependency>
    </dependencies>
```

What should I change?

**Comment by TheMode** [comment]
https://github.com/Minestom/Minestom/wiki/Dependencies
You should add the Minecraft repository, also I've had issues with using the "SNAPSHOT" version with jitpack. I think that you'll be better using the latest commit id (meaning that you'll unfortunately have to update manually)

**Comment by SJS830** [comment]
Adding the minecraft repo wasn't neccesary for me, I just changed the version to `master`.
