### ISSUE TITLE
Extension Improvements

### ISSUE THREAD

**Issue by mworzala** [Minestom/Minestom#529]
Some general improvements which would be good for extensions:
 - [x] Soft dependencies (eg named as a dependency for load order, but allow the extension to start without it)
 - [ ] Version matching (eg depend on LuckPerms 5.x.x specifically)
 - [x] Move to NIO
 - [x] Share external dependencies of the same version between extensions (otherwise there can be conflicts)
 - [x] Common repo names as strings (or just added automatically?), eg
```json
{
    "externalDependencies": {
        "repositories": [
            "MavenCentral",
            "JitPack",
            {"name": "sponge", "url": "..."}
        ],
        "artifacts": ["..."]
    }
}
```
 - [x] Remove `get` prefixes when there is no `set` equivalent
 - [x] Platform dependent external dependencies, see [comment](https://github.com/Minestom/Minestom/issues/529#issuecomment-980143828)
 - [x] ~Revisit extension callback order (`preInitialize` should be called in a phase when startup tasks can still be done)~ Done in #526 
 - [x] "autoscan" mechanism to detect an `extension.json` in the root class loader and automatically load it as an extension. This means if the test server is running with your project classpath (either a main file in `test` or in the future a gradle plugin) the extension will load automagically.
 - [x] Allow `preInitialize` to return a status enum to indicate whether an extension has loaded correctly. If not, it will be unloaded and any dependents will not be loaded
 - [x] ~Registry modification (depends on an internal version of this)~ (for another PR, once the system is closer to finalized)
 - [ ] Internal dependencies (only maven), which are added directly to the extension class loader, instead of a child. (fixes a library loading issue with LWJGL. The two dependencies are isolated meaning it can never find the libraries)

If anything is missed or you disagree, feel free to mention.

Note: Unrelated to #526

**Comment by Articdive** [comment]
I need some OS-specific dependencies, I think it's safe to presume that servers will run on either UNIX (including MacOS) or Windows. would be great if in the artifacts tree.
This is what the past system looked like:
```json
"artifacts:" [
    "org.example:myextension:1.0.0"
]
```
My suggestion allow for the artifacts Block to receive either a direct artifact, or an indirect one with constraints (e.g. OS).
```json
"artifacts:" [
    "org.example:myextension:1.0.0",
    {
        "artifact": "org.example:myextension-${OS}-${ARCHITECTURE}:1.0.0"
        "constraints": {
            "OS": {
                "windows": "win",
                "unix": "linux"
             }
            "ARCHITECTURE": {
                "x86": "x_86",
                "VAM": "vam"
             }
        }
    }
]
```

It can be completely different to the syntax above, but we need a set of keys for server-specific hardware/installations/OS e.g. "windows, unix, x86, arm64" that override the $OS or $ARCHITEXTURE  and unfortuantely they need to be formattable, since some dependencies want ```mydependency-windows``` and some want ```mydependency-win```.

**Comment by mworzala** [comment]
I think that I would propose something like the following instead. It is more verbose than your suggestion but I think it is simpler, and easily allows a situation where you may have a different version on a different os (for example, Minecraft uses LWJGL 3.2.1 on macos)
```json
{
  "artifacts": [
    "org.example:dependency:1.0.0",
    {
      "artifact": "org.lwjgl:lwjgl:3.2.2-natives-windows",
      "os": "windows",
      "arch": "x86_64"
    },
    {
      "artifact": "org.lwjgl:lwjgl:3.2.2-natives-macos",
      "os": "macos",
      "arch": "x86_64"
    },
    {
      "artifact": "org.lwjgl:lwjgl:3.2.2-natives-macos-arm64",
      "os": "macos",
      "arch": "arm64"
    }
  ]
}
```

**Comment by Articdive** [comment]
> I think that I would propose something like the following instead. It is more verbose than your suggestion but I think it is simpler, and easily allows a situation where you may have a different version on a different os (for example, Minecraft uses LWJGL 3.2.1 on macos)
> 
> ```json
> {
>   "artifacts": [
>     "org.example:dependency:1.0.0",
>     {
>       "artifact": "org.lwjgl:lwjgl:3.2.2-natives-windows",
>       "os": "windows",
>       "arch": "x86_64"
>     },
>     {
>       "artifact": "org.lwjgl:lwjgl:3.2.2-natives-macos",
>       "os": "macos",
>       "arch": "x86_64"
>     },
>     {
>       "artifact": "org.lwjgl:lwjgl:3.2.2-natives-macos-arm64",
>       "os": "macos",
>       "arch": "arm64"
>     }
>   ]
> }
> ```
Agreed this makes more sense.

**Comment by CatDevz** [comment]
Maybe remove the requirement to follow semantic versioning, Minestom itself doesn't follow it so making extensions follow it seems silly to me. I personally prefer just using build numbers and/or git commits for versioning, it conveys to me exactly what code is running on my server.
