### ISSUE TITLE
Add instance.dropItem() to InstanceContainer

### ISSUE THREAD

**Issue by nicolasvac** [Minestom/Minestom#579]
When dealing with generators or other objects, you may want to be able to drop some materials.

As we already have setBlock, it would be short and efficient to have a method like this:

```java
instance.dropMaterial(Material material, Pos position, int quantity);
```

**Comment by UnrealValentin** [comment]
when would a world generator want to drop a item?

**Comment by nicolasvac** [comment]
Not a world generator, i meant a generator of items in minigames like in bedwars, every x seconds an item gets dropped from a generator.

**Comment by TheMode** [comment]
You can already spawn entities inside an instance: https://github.com/Minestom/Minestom/blob/1.18/demo/src/main/java/net/minestom/demo/PlayerInit.java#L81-L85
