### ISSUE TITLE
DisplayName in tablist is Component#toString

### ISSUE THREAD

**Issue by SteinGaming** [Minestom/Minestom#581]
![grafik](https://user-images.githubusercontent.com/69219673/148684195-bc3d77e0-5455-4f6e-b1af-ce912d54ba3e.png)
I set the displayName on the PlayerJoinEvent and the Component is created with Component.text("prefix and playername")
Code (Written in kotlin): 
```
player.displayName = Component.text(buildString {
              append(
                     try {
                        Lobby.instance.prefixConfig?.get(
                           "informationList"
                      )?.asJsonArray?.find { e ->
                           e.asJsonObject.get("groupName").asString == group
                       }?.asJsonObject?.get("prefix")?.asString
                 } catch (e: Throwable) {
               null
              } ?: "§7"
        )
      append(name)
})
```

**Comment by MrGazdag** [comment]
What branch is this? `master` or `1.18`?

**Comment by SteinGaming** [comment]
Resolved it, i didnt know that `player.name` was a Component.
Fixed it with putting the first statement in Component.text() and appending it with the name.
