### ISSUE TITLE
getAttribute(attribute).setBaseValue(walkSpeed) reset sprint status on client

### ISSUE THREAD

**Issue by MrBretze** [Minestom/Minestom#589]
I have an issue with 
` player.getAttribute(Attribute.MOVEMENT_SPEED).setBaseValue(speed);`

In Minecraft vanilla, when you update this (with command or via Bukkit), you keep the sprint and the correct walk speed.

In Minestom, the sprint animation is continued, but your walk speed is reset (equivalent of the walk speed but with no sprint), you need to stop sprinting and then restart your sprint to get the correct walk speed

**Comment by mworzala** [comment]
This was fixed in https://github.com/Minestom/Minestom/commit/edb73f0a5ab7ed335160bded34d463535f7becc3
