### ISSUE TITLE
Minecraftserver.setTerminalEnabled not working

### ISSUE THREAD

**Issue by off-by-0point5** [Minestom/Minestom#590]
With the following code, the terminal is started anyway on server start.
```java
MinecraftServer.setTerminalEnabled(false);
MinecraftServer server = MinecraftServer.init();
server.start("localhost", 25565);
```
Using the flag, the terminal is actually disabled.
```java -Dminestom.terminal.disabled -jar ...```

**Comment by TheMode** [comment]
Fixed by 615476fe534e2344b82f3fd74c64d26bea70a005
