### ISSUE TITLE
Minestom doesn't let players connect with Gate proxy

### ISSUE THREAD

**Issue by emortaldev** [Minestom/Minestom#653]
When the proxy sends you to a Minestom server it just loses connection
![image](https://user-images.githubusercontent.com/28760284/152662114-0e71c7ee-3a4f-47e9-b925-e882defa88f0.png)
however Minestom says a player logs on and then leaves

Doesn't work with both Velocity and Bungee forwarding

**Comment by TheMode** [comment]
Did you try without any forwarding? I am not familiar with the project so I am unlikely to fix it.

**Comment by emortaldev** [comment]
Doesn't work without forwarding either

**Comment by nicolasvac** [comment]
Did you enable VelocityProxy.init ?

**Comment by emortaldev** [comment]
Yes, but even with no forwarding it doesn't work
