### ISSUE TITLE
Viewable Rule not updating

### ISSUE THREAD

**Issue by Jacrispys** [Minestom/Minestom#696]
When creating a viewable rule for a command, It seems to only update on player join, and not when called by a method.

https://www.toptal.com/developers/hastebin/xibasubeqi.java

**Comment by Jacrispys** [comment]
More Minimal Scenario, barebones server + command to update the rule VIA tags

https://www.toptal.com/developers/hastebin/homiwibofo.java

**Comment by TheMode** [comment]
Your predicate must retrieve the tag from the player itself instead of the potential viewer.

Replace
```java
Predicate<Player> vanishRule = p -> Boolean.TRUE.equals(p.getTag(IS_PLAYER_VISIBLE));
```
to
```java
Predicate<Player> vanishRule = p -> Boolean.TRUE.equals(player.getTag(IS_PLAYER_VISIBLE));
```
