### ISSUE TITLE
Property "falling" is not settable (water and lava)

### ISSUE THREAD

**Issue by ElAndree** [Minestom/Minestom#703]
Hey there,

with the current implementation, it is not possible to set the falling property for water/lava.
I think this is a bug :)

`java.lang.IllegalArgumentException: Property falling is not valid for block minecraft:water{properties={level=>0}, nbt=null, handler=null}
	at net.minestom.server.instance.block.BlockImpl.withProperty(BlockImpl.java:139)`
	
Kind regards
Andre

**Comment by TheMode** [comment]
This property does not exist. Where did you see it?

**Comment by ElAndree** [comment]
My client says this is existing

![image](https://user-images.githubusercontent.com/39100879/154822570-46e882c3-c329-4a2e-87cd-dd63f0d24a82.png)

**Comment by ZakShearman** [comment]
They only have the `level` property. This should explain it and is from Spigot's JavaDocs:

In the case of water and lava blocks the levels have special meanings: a level of 0 corresponds to a source block, 1-7 regular fluid heights, and 8-15 to "falling" fluids. All falling fluids have the same behaviour, but the level corresponds to that of the block above them, equal to this.level - 8 Note that counterintuitively, an adjusted level of 1 is the highest level, whilst 7 is the lowest

**Comment by TheMode** [comment]
Unrelated to block properties.
