### ISSUE TITLE
Block collision bug

### ISSUE THREAD

**Issue by ElAndree** [Minestom/Minestom#765]
So in vanilla if i stand sneaking at the edge of the corner block and place one block below its working
- in minestom its not working

I think thats a bug :)

![image](https://user-images.githubusercontent.com/39100879/158200477-496de1d6-7584-4f31-a474-1cef8cf3b32f.png)
![image](https://user-images.githubusercontent.com/39100879/158200486-a7f6ce95-3e7c-431e-9e8f-3ef3ed590f5b.png)

**Comment by TheMode** [comment]
Should be fixed by bcfb4c6ea4d82228aca4336066efe7ab66460ad3
