### ISSUE TITLE
ChatColor.DARK_CYAN is broken

### ISSUE THREAD

**Issue by Geolykt** [Minestom/Minestom#77]
### What is the current behaviour?
Usage of ChatColor.DARK_CYAN results in the color of the following text being set to white

### What is the expected behaviour?
Usage of ChatColor.DARK_CYAN results in the color of the following text being set to a more blue-greenish color

### What steps will reproduce the problem?
```java
Command debugCyan = new Command("cyan");
debugCyan.setDefaultExecutor((sender, args) -> {
    sender.sendMessage(ChatColor.DARK_CYAN + "This text should be in dark cyan.");
    MinecraftServer.getConnectionManager().broadcastMessage(ColoredText.of(ChatColor.DARK_CYAN + "This text should be in dark cyan."));
    MinecraftServer.getConnectionManager().broadcastMessage(ColoredText.of(ChatColor.DARK_CYAN, "This text should be in dark cyan."));
});
MinecraftServer.getCommandManager().register(debugCyan);
```
All three resulting lines will be in white if the command `/cyan` is invoked

### What operating system and java version is being used?
    Java 11.0.9.1 (OpenJDK obtained from vendor)
    Fedora 33
    Minestom ed46bd0dc2 (Build from Wed Dec 16 03:12:59 UTC 2020) for both server and extension used

### Additional information / Possible thoughts on why this bug is happening
The ChatColor.DARK_CYAN is correctly replaced with "{#dark_cyan}" (at least to my tests), and the decompiled output of the ChatColor class appear to also be fine, so I don't have a real idea why this is happening

**Comment by TheMode** [comment]
Issue was that the internal name for the color is "dark_aqua", should be fixed
