### ISSUE TITLE
ConcurrentModificationException when unregistering instances quickly

### ISSUE THREAD

**Issue by Archy-X** [Minestom/Minestom#79]
### What is the current behavior?

A ConcurrentModificationException occurs when unregistering multiple instances in a row (through a scheduler).

### What is the expected behavior?

There should not be an error

### What steps will reproduce the problem?

1. Create many InstanceContainers.
2. In a scheduled task (not sure if it errors outside of a scheduled task), use `MinecraftServer.getInstanceManager().unregisterInstance(instance);`
3. Check console for error

### What operating system and java version is being used?

Windows 10, Java 11

### If there is an exception, use pastebin/hastebin (NB: no expiry date!) to send the stacktrace

https://pastebin.com/AYyMVUsX

The Removed instance with id _ messages are messages I send when an instance is removed.

### Additional information / Possible thoughts on why this bug is happening

Perhaps use a ConcurrentHashMap instead to make it thread-safe or don't call the UNSAFE_unloadChunks method when unregistering.

**Comment by TheMode** [comment]
Should be fixed, it is because the "chunks to unload Set" is not thread-safe. The reason is that I'd like to avoid using a CopyOnWrite collection
