### ISSUE TITLE
The sign's not loaded below y = 0

### ISSUE THREAD

**Issue by DustKing5** [Minestom/Minestom#808]
Minestom version: 8dcb3191f6

The world created in 1.18.2

![2022-03-25_22 31 37](https://user-images.githubusercontent.com/67860797/160203391-58006c05-cc65-434f-8256-81544107741a.png)

**Comment by Marlonzockt** [comment]
Have you tried the fix discussed in #661 already? (Part is in the question, part in the answer). That might fix it

**Comment by DustKing5** [comment]
Yes, that's the first thing what I tried

**Comment by DustKing5** [comment]
After a few experiments, I noticed that I experience this error under y = 0

**Comment by TheMode** [comment]
Could you provide a reproducer?

**Comment by DustKing5** [comment]
`InstanceManager instanceManager = MinecraftServer.getInstanceManager();`
`instanceContainer = instanceManager.createInstanceContainer(new AnvilLoader("world"));`

Compressed world folder:
[world.zip](https://github.com/Minestom/Minestom/files/8355087/world.zip)

**Comment by TheMode** [comment]
Should be fixed by 740ffc884684e37bdbfa90f1c904a38c0e2ed7ce
