### ISSUE TITLE
Velocity packet bug

### ISSUE THREAD

**Issue by HttpMarco** [Minestom/Minestom#863]
The handshake packet write wrong velocity informations 

`    public HandshakePacket(BinaryReader reader) {
        this(reader.readVarInt(), reader.readSizedString(BungeeCordProxy.isEnabled() ? Short.MAX_VALUE : 255),
                reader.readUnsignedShort(), reader.readVarInt());
    }`

**Comment by GreatWyrm** [comment]
This may have been fixed by e5d0a43ba42c7023a93e8e33356909e614783ac7, can someone confirm this?
