### ISSUE TITLE
ItemEntity is not thread-safe

### ISSUE THREAD

**Issue by programmerpony** [Minestom/Minestom#9]
### What is the current behavior?
The server is deadlocked, entity pool threads are blocked 100% of the time. Clients time out.

### What is the expected behavior?
CPU usage to scale with the amount of item entities.

### What steps will reproduce the problem?
Throw a lot (~700 for me) of items on the ground that don't merge. This is easily done by throwing them directly from the creative inventory tabs. 

![](https://user-images.githubusercontent.com/66215615/83363662-1fe1b280-a369-11ea-8cbc-334574c9642b.png)

### What java version is being used?
OpenJDK 11

### If there is an exception, use pastebin/hastebin (NB: no expiry date!) to send the stacktrace
Entity pool thread dump: https://pastebin.com/raw/qwGsNmRy

### Additional information / Possible thoughts on why this bug is happening
>"Ms-EntitiesPool-9" #26 prio=5 os_prio=0 cpu=62001.28ms elapsed=1883.55s tid=0x00007f94d8010800 nid=0x190b4 waiting for monitor entry  [0x00007f94d68f8000]
>   java.lang.Thread.State: BLOCKED (on object monitor)
>        at net.minestom.server.entity.ItemEntity.update(ItemEntity.java:52)
>        - waiting to lock <0x0000000092a20a28> (a net.minestom.server.entity.ItemEntity)
>        - locked <0x000000008cac8028> (a net.minestom.server.entity.ItemEntity)

>"Ms-EntitiesPool-10" #27 prio=5 os_prio=0 cpu=62437.06ms elapsed=1883.51s tid=0x00007f94d8012000 nid=0x190b5 waiting for monitor entry  [0x00007f94d66f5000]
>   java.lang.Thread.State: BLOCKED (on object monitor)
>        at net.minestom.server.entity.ItemEntity.update(ItemEntity.java:52)
>        - waiting to lock <0x000000008cac8028> (a net.minestom.server.entity.ItemEntity)
>        - locked <0x0000000092a20a28> (a net.minestom.server.entity.ItemEntity)

The two threads both hold one of the two objects they both want. They're both blocked waiting for the other to release the other object. This issue is caused by [ItemEntity::update()](https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/entity/ItemEntity.java#L52) locking `this` and then the item entity it checks to see if it can merge with.

**Comment by TheMode** [comment]
Good find, did set the class as a monitor instead and I added an update cooldown to mitigate its impact.

This can be a temporary solution, feel free to say or add a pull request if you find any better solution
