### ISSUE TITLE
Exact position that item was used on a block is not exposed

### ISSUE THREAD

**Issue by emortaldev** [Minestom/Minestom#905]
### Discussed in https://github.com/Minestom/Minestom/discussions/853

<div type='discussions-op-text'>

<sup>Originally posted by **emortaldev** April  3, 2022</sup>
I am attempting to make a firework item, however it rounds to a block with item use event, does the spigot server normally do raycasting?</div>

**Comment by Marlonzockt** [comment]
#893 would make possible I think

**Comment by MrGazdag** [comment]
so would #443 (which #893) includes

**Comment by luzzardik** [comment]
Spigot doesn't do any raycasting, it uses the packet data; which is exposed in Block Handlers but not Placement Rules.

**Comment by emortaldev** [comment]
This is the same for entity InteractAt, that also isn't exposed

**Comment by mworzala** [comment]
Fixed with #1937
