### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by RinesThaix** [Minestom/Minestom#911]
Entity#tick -> Entity#touchTick -> ChunkCache#getBlock -> synchronized(chunk) leads to a deadlock at unknown cirmunstances. Unfortunately I don't know another blocking trace, but will continue investigating.

**Comment by Eoghanmc22** [comment]
idk if you know this already but jprofiler is really good for this

**Comment by TheMode** [comment]
Do you have a custom `Chunk` implementation?

**Comment by RinesThaix** [comment]
@Eoghanmc22 I know, but server stopped before I could see waiting thread.
@TheMode no.
