### ISSUE TITLE
NullPointerException within ShapeImpl

### ISSUE THREAD

**Issue by RinesThaix** [Minestom/Minestom#913]
![image](https://user-images.githubusercontent.com/3867723/163145191-e632bc5a-5b94-4673-ac50-8a698898ea35.png)

Basically what's happening:
- https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/registry/Registry.java#L199 sets block material supplier to null, because there's no `correspondingItem` field within parsed block json.
- `ShapeImpl` is being created with that supplier, but it also tries to invoke that supplier to get material and then retrieve it's block state at https://github.com/Minestom/Minestom/blob/master/src/main/java/net/minestom/server/collision/ShapeImpl.java#L100.

Not familiar with that code and not really sure how to fix it, would really appreciate your help.

**Comment by TheMode** [comment]
Fixed by 50a7d7ca81771b7900e224aa68ee7763b660d477

This was already present in the `light` branch but unfortunately still WIP
