### ISSUE TITLE
You can sometimes place blocks inside yourself

### ISSUE THREAD

**Issue by emortaldev** [Minestom/Minestom#930]
[Video as example](https://cdn.discordapp.com/attachments/706185253974442006/965023045146275870/minestomblockplacementbug.mp4)

(second clip doesn't really show much extra, is also very high ping situation, maybe ignore second clip)

**Comment by Bloepiloepi** [comment]
Seems to be caused by this line: https://github.com/Minestom/Minestom/blob/634d2c87b7085a376acc0824fa06562524daf887/src/main/java/net/minestom/server/collision/BlockCollision.java#L346

I changed 0.01 to 0.00001 and the issue does rarely happen anymore. It is not a perfect solution however

**Comment by Bloepiloepi** [comment]
The vanilla server uses the constant 0.0000001

**Comment by TheMode** [comment]
Fixed by #940
