### ISSUE TITLE
Using setNotifyAboutChanges appears to ignore some entity meta

### ISSUE THREAD

**Issue by emortaldev** [Minestom/Minestom#942]
[Video for example](https://cdn.discordapp.com/attachments/706185253974442006/965626658323300432/2022-04-18_15-51-40.mp4)
[Code to reproduce](https://bin.bloom.host/uniroyesuz.swift)

In the video you can see when I type reset2 (the one without `setNotifyAboutChanges`) everything works fine, but when I do reset it does not send certain information at all (e.g. setGravity) or delays them until another action (e.g. setInvisible seemed to fix itself after I crouched)

**Comment by WeiiswurstDev** [comment]
This could be because the notify changes list gets cleared [here](https://github.com/Minestom/Minestom/blob/96fee8541dcbdc2d3b03c0795af42454e7aa784a/src/main/java/net/minestom/server/entity/Metadata.java#L217) even though it is used later on to send the changes to the player.

**Comment by WeiiswurstDev** [comment]
> This could be because the notify changes list gets cleared [here](https://github.com/Minestom/Minestom/blob/96fee8541dcbdc2d3b03c0795af42454e7aa784a/src/main/java/net/minestom/server/entity/Metadata.java#L217) even though it is used later on to send the changes to the player.

This actually was the fix, see #962
