### ISSUE TITLE
Entities always have some downward velocity

### ISSUE THREAD

**Issue by Steanky** [Minestom/Minestom#967]
What the title says — stationary entities (standing on a block) have a velocity of [0, -1.568, 0]. Testing with a field watchpoint and logging the value showed that the `velocity` field is constantly (every tick) being set to this value by `velocityTick()`. 

Here's the code I used to spawn the entity:

```java
MinecraftServer.getGlobalEventHandler().addListener(PlayerChatEvent.class, event -> {
    String msg = event.getMessage();
    Player player = event.getPlayer();
    Instance instance = player.getInstance();

    if(instance != null) {
        switch (msg) {
            case "ZZZ" -> {
                EntityCreature creature = new EntityCreature(EntityType.ZOMBIE);
                creature.setInstance(instance, player.getPosition().add(5, 0, 0));
            }
        }
    }
});
```

I was using 765d6057da0bb9882ce31973e6f78be32f340c4d, though I'm technically running a minor fork that only implements a few (unrelated) changes. I tested on again on e2dac1c46ee01d99e50aab3deef99127424a9adb, right before the `takeKnockback` and gravity fixes, and velocity reads as expected. So I'm assuming it's something to do with how gravity is applied, though I don't know exactly what.

**Comment by Bloepiloepi** [comment]
It's intentional, and also the case in vanilla. Do you think it is a problem?

**Comment by Steanky** [comment]
> It's intentional, and also the case in vanilla. Do you think it is a problem?

I don't think it would be a problem, except for the fact that `hasVelocity` returns `true` for entities that are completely stationary. Intuitively, I though it would return `false` (this was obviously the old behavior). Consequently, EntityVelocityPackets are being sent to all viewers every tick even for stationary entities. Not sure if this last part is vanilla or not, though.

**Comment by Bloepiloepi** [comment]
I agree that it doesn't make sense for `hasVelocity` to return `true` if the entity is stationary
