### ISSUE TITLE
Arrows and other entities such as spectators prevent blocks from being placed

### ISSUE THREAD

**Issue by CatDevz** [Minestom/Minestom#992]
### Discussed in https://github.com/Minestom/Minestom/discussions/982

Maybe some metadata can be used to determine if blocks can be placed where the entity is?

<div type='discussions-op-text'>

<sup>Originally posted by **CatDevz** April 25, 2022</sup>
Arrows are preventing blocks from being placed, is there any way to exclude arrows/specific entities from preventing block placement? Thanks.

Edit: In addition to this players in spectator
</div>

**Comment by TheMode** [comment]
It has been fixed in 9ce5a79cc8bc55ae1f3636f6f496792830f2f159
